// lib/donusum-data.ts
// Tüm dönüşüm çiftleri ve kategori verileri

export type ConverterType =
  | 'canvas'
  | 'heic2any'
  | 'ffmpeg'
  | 'pdf-lib'
  | 'mammoth'
  | 'sheetjs'
  | 'jszip'
  | 'subsrt'
  | 'whisper'
  | 'tesseract';

export interface Secenek {
  id: string;
  label: { en: string };
  type: 'range' | 'select' | 'checkbox';
  default: string | number | boolean;
  min?: number;
  max?: number;
  step?: number;
  options?: { value: string; label: string }[];
  unit?: string;
}

export interface DonusumCift {
  slug: string;
  from: string;
  to: string;
  fromExt: string;
  toExt: string;
  kategori: KategoriSlug;
  converter: ConverterType;
  baslik: { en: string };
  aciklama: { en: string };
  populer: boolean;
  secenekler?: Secenek[];
  cokluDosya?: boolean;
  ffmpegArgs?: string[];
}

export type KategoriSlug = 'goruntu' | 'video' | 'ses' | 'belge' | 'arsiv' | 'altyazi' | 'desifre';

export interface Kategori {
  slug: KategoriSlug;
  baslik: { en: string };
  aciklama: { en: string };
  ikon: string;
  renk: string;
}

export const KATEGORILER: Kategori[] = [
  {
    slug: 'goruntu',
    baslik: { en: 'Image' },
    aciklama: { en: 'Convert between JPG, PNG, WebP, SVG, HEIC and more image formats.' },
    ikon: '🖼️',
    renk: '#ff4d6d',
  },
  {
    slug: 'video',
    baslik: { en: 'Video' },
    aciklama: { en: 'Convert MP4, WebM, AVI, MOV and other video formats.' },
    ikon: '🎬',
    renk: '#ff8c42',
  },
  {
    slug: 'ses',
    baslik: { en: 'Audio' },
    aciklama: { en: 'Convert between MP3, WAV, OGG, AAC and other audio formats.' },
    ikon: '🎵',
    renk: '#ffd166',
  },
  {
    slug: 'belge',
    baslik: { en: 'Document' },
    aciklama: { en: 'Convert PDF, DOCX, TXT, CSV and other document formats.' },
    ikon: '📄',
    renk: '#06d6a0',
  },
  {
    slug: 'arsiv',
    baslik: { en: 'Archive' },
    aciklama: { en: 'Create and extract ZIP archives.' },
    ikon: '📦',
    renk: '#4d9fff',
  },
  {
    slug: 'altyazi',
    baslik: { en: 'Subtitle' },
    aciklama: { en: 'Convert SRT, VTT, SUB subtitle files.' },
    ikon: '📝',
    renk: '#ffb703',
  },
  {
    slug: 'desifre',
    baslik: { en: 'Transcription' },
    aciklama: { en: 'Transcribe audio files to text using AI directly in your browser.' },
    ikon: '🎙️',
    renk: '#06d6a0',
  },
];

const KATEGORI_SLUG_TO_EN: Record<string, string> = {
  'goruntu': 'image',
  'video': 'video',
  'ses': 'audio',
  'belge': 'document',
  'arsiv': 'archive',
  'altyazi': 'subtitle',
  'desifre': 'transcription',
};

export function getCategoryPath(catSlug: string): string {
  return `/en/category/${KATEGORI_SLUG_TO_EN[catSlug] || catSlug}`;
}

export function getDonusumPath(slug: string): string {
  const tool = DONUSUM_DATA.find(d => d.slug === slug);
  if (!tool) return `/en/${slug}`; // Fallback if tool not found

  const catPath = getCategoryPath(tool.kategori);
  return `${catPath}/${slug}`;
}

export function getTranslatedFormat(format: string): string {
  const enMap: Record<string, string> = {
    'Görseller': 'Images',
    'Dosyalar': 'Files',
  };
  return enMap[format] || format;
}

export const WHISPER_LANGUAGES = [
  { value: 'auto', label: 'Auto Detect / Otomatik Algıla' },
  { value: 'turkish', label: 'Türkçe (Turkish)' },
  { value: 'english', label: 'English' },
  { value: 'spanish', label: 'Español (Spanish)' },
  { value: 'french', label: 'Français (French)' },
  { value: 'german', label: 'Deutsch (German)' },
  { value: 'italian', label: 'Italiano (Italian)' },
  { value: 'portuguese', label: 'Português (Portuguese)' },
  { value: 'russian', label: 'Русский (Russian)' },
  { value: 'chinese', label: '中文 (Chinese)' },
  { value: 'japanese', label: '日本語 (Japanese)' },
  { value: 'korean', label: '한국어 (Korean)' },
  { value: 'arabic', label: 'العربية (Arabic)' },
  { value: 'dutch', label: 'Nederlands (Dutch)' },
  { value: 'polish', label: 'Polski (Polish)' },
  { value: 'greek', label: 'Ελληνικά (Greek)' },
  { value: 'hindi', label: 'हिन्दी (Hindi)' },
  { value: 'swedish', label: 'Svenska (Swedish)' },
  { value: 'ukrainian', label: 'Українська (Ukrainian)' },
  { value: 'vietnamese', label: 'Tiếng Việt (Vietnamese)' },
  { value: 'indonesian', label: 'Bahasa Indonesia (Indonesian)' },
  { value: 'malay', label: 'Bahasa Melayu (Malay)' },
  { value: 'thai', label: 'ไทย (Thai)' },
  { value: 'czech', label: 'Čeština (Czech)' },
  { value: 'danish', label: 'Dansk (Danish)' },
  { value: 'finnish', label: 'Suomi (Finnish)' },
  { value: 'hebrew', label: 'עברית (Hebrew)' },
  { value: 'hungarian', label: 'Magyar (Hungarian)' },
  { value: 'norwegian', label: 'Norsk (Norwegian)' },
  { value: 'romanian', label: 'Română (Romanian)' },
  { value: 'slovak', label: 'Slovenčina (Slovak)' },
  { value: 'catalan', label: 'Català (Catalan)' },
  { value: 'bulgarian', label: 'Български (Bulgarian)' },
  { value: 'croatian', label: 'Hrvatski (Croatian)' },
  { value: 'serbian', label: 'Српски (Serbian)' },
  { value: 'slovenian', label: 'Slovenščina (Slovenian)' },
  { value: 'lithuanian', label: 'Lietuvių (Lithuanian)' },
  { value: 'latvian', label: 'Latviešu (Latvian)' },
  { value: 'estonian', label: 'Eesti (Estonian)' },
  { value: 'azerbaijani', label: 'Azərbaycanca (Azerbaijani)' },
  { value: 'georgian', label: 'Ქართული (Georgia)' },
  { value: 'armenian', label: 'Հայերեն (Armenian)' },
  { value: 'persian', label: 'فارسی (Persian)' },
  { value: 'urdu', label: 'اردو (Urdu)' },
  { value: 'bengali', label: 'বাংলা (Bengali)' },
  { value: 'tamil', label: 'தமிழ் (Tamil)' },
  { value: 'telugu', label: 'తెలుగు (Telugu)' },
  { value: 'malayalam', label: 'മലയാളം (Malayalam)' },
  { value: 'kannada', label: 'ಕನ್ನಡ (Kannada)' },
  { value: 'marathi', label: 'मराठी (Marathi)' },
  { value: 'gujarati', label: 'ગુજરાતી (Gujarati)' },
  { value: 'punjabi', label: 'ਪੰਜਾਬੀ (Punjabi)' },
  { value: 'kazakh', label: 'Қазақша (Kazakh)' },
  { value: 'uzbek', label: 'Oʻzbekcha (Uzbek)' },
  { value: 'albanian', label: 'Shqip (Albanian)' },
  { value: 'bosnian', label: 'Bosanski (Bosnian)' },
  { value: 'macedonian', label: 'Македонски (Macedonian)' },
  { value: 'welsh', label: 'Cymraeg (Welsh)' },
  { value: 'icelandic', label: 'Íslenska (Icelandic)' },
  { value: 'galician', label: 'Galego (Galician)' },
  { value: 'basque', label: 'Euskara (Basque)' },
  { value: 'swahili', label: 'Kiswahili (Swahili)' },
  { value: 'tagalog', label: 'Tagalog (Tagalog/Filipino)' },
  { value: 'afrikaans', label: 'Afrikaans' },
  { value: 'latin', label: 'Latina (Latin)' },
  { value: 'mongolian', label: 'Монгол (Mongolian)' },
  { value: 'nepali', label: 'नेपाली (Nepali)' },
  { value: 'belarusian', label: 'Беларуская (Belarusian)' }
];

export const OCR_LANGUAGES = [
  { value: 'tur+eng', label: 'Türkçe + English' },
  { value: 'tur', label: 'Türkçe (Turkish)' },
  { value: 'eng', label: 'English' },
  { value: 'deu', label: 'Deutsch (German)' },
  { value: 'fra', label: 'Français (French)' },
  { value: 'spa', label: 'Español (Spanish)' },
  { value: 'ita', label: 'Italiano (Italian)' },
  { value: 'por', label: 'Português (Portuguese)' },
  { value: 'rus', label: 'Русский (Russian)' },
  { value: 'ara', label: 'العربية (Arabic)' },
];

export const DONUSUM_DATA: DonusumCift[] = [
  // ===== GÖRÜNTÜ =====
  {
    slug: 'jpg-to-png',
    from: 'JPG',
    to: 'PNG',
    fromExt: 'jpg',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → PNG Converter' },
    aciklama: { en: 'Convert your JPG files to PNG format with transparent background support. Lossless quality, entirely in your browser.' },
    populer: true,
  },
  {
    slug: 'png-to-jpg',
    from: 'PNG',
    to: 'JPG',
    fromExt: 'png',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → JPG Converter' },
    aciklama: { en: 'Convert your PNG files to smaller-sized JPG format. Optimize file size by adjusting the quality.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality' },
        type: 'range',
        default: 92,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'jpg-to-webp',
    from: 'JPG',
    to: 'WebP',
    fromExt: 'jpg',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → WebP Converter' },
    aciklama: { en: 'Convert your JPG files to modern WebP format. Smaller size, same quality.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality' },
        type: 'range',
        default: 85,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'png-to-webp',
    from: 'PNG',
    to: 'WebP',
    fromExt: 'png',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → WebP Converter' },
    aciklama: { en: 'Convert your PNG images to WebP format. Transparency is preserved, size is reduced.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality' },
        type: 'range',
        default: 85,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'webp-to-png',
    from: 'WebP',
    to: 'PNG',
    fromExt: 'webp',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → PNG Converter' },
    aciklama: { en: 'Convert your WebP images to the common PNG format.' },
    populer: true,
  },
  {
    slug: 'webp-to-jpg',
    from: 'WebP',
    to: 'JPG',
    fromExt: 'webp',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → JPG Converter' },
    aciklama: { en: 'Convert your WebP images to JPG format.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality' },
        type: 'range',
        default: 92,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'heic-to-jpg',
    from: 'HEIC',
    to: 'JPG',
    fromExt: 'heic',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'heic2any',
    baslik: { en: 'HEIC → JPG Converter' },
    aciklama: { en: 'Convert your iPhone HEIC photos to JPG format. Make them viewable everywhere.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality' },
        type: 'range',
        default: 92,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'heic-to-png',
    from: 'HEIC',
    to: 'PNG',
    fromExt: 'heic',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'heic2any',
    baslik: { en: 'HEIC → PNG Converter' },
    aciklama: { en: 'Convert your iPhone HEIC photos to transparent PNG format.' },
    populer: true,
  },
  {
    slug: 'svg-to-png',
    from: 'SVG',
    to: 'PNG',
    fromExt: 'svg',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'SVG → PNG Converter' },
    aciklama: { en: 'Convert your vector SVG files to pixel-based PNG format.' },
    populer: false,
  },
  {
    slug: 'bmp-to-png',
    from: 'BMP',
    to: 'PNG',
    fromExt: 'bmp',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → PNG Converter' },
    aciklama: { en: 'Convert your BMP files to compressed PNG format.' },
    populer: false,
  },
  {
    slug: 'gif-to-png',
    from: 'GIF',
    to: 'PNG',
    fromExt: 'gif',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → PNG Converter' },
    aciklama: { en: 'Convert the first frame of your GIF files to PNG format.' },
    populer: false,
  },
  {
    slug: 'jpg-to-bmp',
    from: 'JPG',
    to: 'BMP',
    fromExt: 'jpg',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → BMP Converter' },
    aciklama: { en: 'Convert your JPG images to BMP format.' },
    populer: false,
  },
  {
    slug: 'jpg-to-gif',
    from: 'JPG',
    to: 'GIF',
    fromExt: 'jpg',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → GIF Converter' },
    aciklama: { en: 'Convert your JPG images to GIF format (first frame).' },
    populer: false,
  },
  {
    slug: 'png-to-bmp',
    from: 'PNG',
    to: 'BMP',
    fromExt: 'png',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → BMP Converter' },
    aciklama: { en: 'Convert your PNG images to BMP format.' },
    populer: false,
  },
  {
    slug: 'png-to-gif',
    from: 'PNG',
    to: 'GIF',
    fromExt: 'png',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → GIF Converter' },
    aciklama: { en: 'Convert your PNG images to GIF format.' },
    populer: false,
  },
  {
    slug: 'webp-to-bmp',
    from: 'WebP',
    to: 'BMP',
    fromExt: 'webp',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → BMP Converter' },
    aciklama: { en: 'Convert your WebP images to BMP format.' },
    populer: false,
  },
  {
    slug: 'webp-to-gif',
    from: 'WebP',
    to: 'GIF',
    fromExt: 'webp',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → GIF Converter' },
    aciklama: { en: 'Convert your WebP images to GIF format.' },
    populer: false,
  },
  {
    slug: 'heic-to-webp',
    from: 'HEIC',
    to: 'WebP',
    fromExt: 'heic',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'heic2any',
    baslik: { en: 'HEIC → WebP Converter' },
    aciklama: { en: 'Convert HEIC images to modern WebP format.' },
    populer: false,
  },
  {
    slug: 'svg-to-jpg',
    from: 'SVG',
    to: 'JPG',
    fromExt: 'svg',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'SVG → JPG Converter' },
    aciklama: { en: 'Convert vector SVG files to JPG format.' },
    populer: false,
  },
  {
    slug: 'svg-to-webp',
    from: 'SVG',
    to: 'WebP',
    fromExt: 'svg',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'SVG → WebP Converter' },
    aciklama: { en: 'Convert vector SVG files to WebP format.' },
    populer: false,
  },
  {
    slug: 'bmp-to-jpg',
    from: 'BMP',
    to: 'JPG',
    fromExt: 'bmp',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → JPG Converter' },
    aciklama: { en: 'Convert BMP images to JPG format.' },
    populer: false,
  },
  {
    slug: 'bmp-to-webp',
    from: 'BMP',
    to: 'WebP',
    fromExt: 'bmp',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → WebP Converter' },
    aciklama: { en: 'Convert BMP images to WebP format.' },
    populer: false,
  },
  {
    slug: 'bmp-to-gif',
    from: 'BMP',
    to: 'GIF',
    fromExt: 'bmp',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → GIF Converter' },
    aciklama: { en: 'Convert BMP images to GIF format.' },
    populer: false,
  },
  {
    slug: 'gif-to-jpg',
    from: 'GIF',
    to: 'JPG',
    fromExt: 'gif',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → JPG Converter' },
    aciklama: { en: 'Convert GIF images to JPG format.' },
    populer: false,
  },
  {
    slug: 'gif-to-webp',
    from: 'GIF',
    to: 'WebP',
    fromExt: 'gif',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → WebP Converter' },
    aciklama: { en: 'Convert GIF images to WebP format.' },
    populer: false,
  },
  {
    slug: 'gif-to-bmp',
    from: 'GIF',
    to: 'BMP',
    fromExt: 'gif',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → BMP Converter' },
    aciklama: { en: 'Convert GIF images to BMP format.' },
    populer: false,
  },


  // ===== VİDEO =====
  {
    slug: 'mp4-to-webm',
    from: 'MP4',
    to: 'WebM',
    fromExt: 'mp4',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → WebM Converter' },
    aciklama: { en: 'Convert your MP4 videos to open-source WebM format. Optimized for the web.' },
    populer: true,
    ffmpegArgs: ['-c:v', 'libvpx-vp9', '-crf', '30', '-b:v', '0', '-c:a', 'libopus'],
  },
  {
    slug: 'mp4-to-avi',
    from: 'MP4',
    to: 'AVI',
    fromExt: 'mp4',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → AVI Converter' },
    aciklama: { en: 'Convert your MP4 videos to AVI format.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'mpeg4', '-vtag', 'xvid', '-qscale:v', '3', '-c:a', 'libmp3lame'],
  },
  {
    slug: 'mp4-to-mov',
    from: 'MP4',
    to: 'MOV',
    fromExt: 'mp4',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → MOV Converter' },
    aciklama: { en: 'Convert your MP4 videos to Apple MOV format.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'copy', '-c:a', 'copy'],
  },
  {
    slug: 'mp4-to-mkv',
    from: 'MP4',
    to: 'MKV',
    fromExt: 'mp4',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → MKV Converter' },
    aciklama: { en: 'Convert your MP4 videos to MKV format.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'copy', '-c:a', 'copy'],
  },
  {
    slug: 'webm-to-mp4',
    from: 'WebM',
    to: 'MP4',
    fromExt: 'webm',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MP4 Converter' },
    aciklama: { en: 'Convert your WebM videos to the common MP4 format.' },
    populer: true,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'avi-to-mp4',
    from: 'AVI',
    to: 'MP4',
    fromExt: 'avi',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MP4 Converter' },
    aciklama: { en: 'Convert your old AVI videos to modern MP4 format.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'mov-to-mp4',
    from: 'MOV',
    to: 'MP4',
    fromExt: 'mov',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → MP4 Converter' },
    aciklama: { en: 'Convert your Apple MOV videos to MP4 format. Play on any device.' },
    populer: true,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'mp4-to-gif',
    from: 'MP4',
    to: 'GIF',
    fromExt: 'mp4',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → GIF Converter' },
    aciklama: { en: 'Convert your video clips to animated GIF files.' },
    populer: true,
    ffmpegArgs: ['-vf', 'fps=15,scale=480:-1:flags=lanczos', '-loop', '0'],
  },
  {
    slug: 'mkv-to-mp4',
    from: 'MKV',
    to: 'MP4',
    fromExt: 'mkv',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → MP4 Converter' },
    aciklama: { en: 'Convert your MKV videos to compatible MP4 format.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'mp4-to-flv',
    from: 'MP4',
    to: 'FLV',
    fromExt: 'mp4',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → FLV Converter' },
    aciklama: { en: 'Convert MP4 videos to FLV format.' },
    populer: false,
  },
  {
    slug: 'mp4-to-wmv',
    from: 'MP4',
    to: 'WMV',
    fromExt: 'mp4',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → WMV Converter' },
    aciklama: { en: 'Convert MP4 videos to WMV format.' },
    populer: false,
  },
  {
    slug: 'webm-to-avi',
    from: 'WebM',
    to: 'AVI',
    fromExt: 'webm',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → AVI Converter' },
    aciklama: { en: 'Convert WebM videos to AVI format.' },
    populer: false,
  },
  {
    slug: 'webm-to-mov',
    from: 'WebM',
    to: 'MOV',
    fromExt: 'webm',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MOV Converter' },
    aciklama: { en: 'Convert WebM videos to Apple MOV format.' },
    populer: false,
  },
  {
    slug: 'webm-to-mkv',
    from: 'WebM',
    to: 'MKV',
    fromExt: 'webm',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MKV Converter' },
    aciklama: { en: 'Convert WebM videos to MKV format.' },
    populer: false,
  },
  {
    slug: 'webm-to-flv',
    from: 'WebM',
    to: 'FLV',
    fromExt: 'webm',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → FLV Converter' },
    aciklama: { en: 'Convert WebM videos to FLV format.' },
    populer: false,
  },
  {
    slug: 'webm-to-wmv',
    from: 'WebM',
    to: 'WMV',
    fromExt: 'webm',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → WMV Converter' },
    aciklama: { en: 'Convert WebM videos to WMV format.' },
    populer: false,
  },
  {
    slug: 'webm-to-gif',
    from: 'WebM',
    to: 'GIF',
    fromExt: 'webm',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → GIF Converter' },
    aciklama: { en: 'Convert WebM videos to animated GIF files.' },
    populer: false,
  },
  {
    slug: 'avi-to-webm',
    from: 'AVI',
    to: 'WebM',
    fromExt: 'avi',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → WebM Converter' },
    aciklama: { en: 'Convert AVI videos to open-source WebM format.' },
    populer: false,
  },
  {
    slug: 'avi-to-mov',
    from: 'AVI',
    to: 'MOV',
    fromExt: 'avi',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MOV Converter' },
    aciklama: { en: 'Convert AVI videos to Apple MOV format.' },
    populer: false,
  },
  {
    slug: 'avi-to-mkv',
    from: 'AVI',
    to: 'MKV',
    fromExt: 'avi',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MKV Converter' },
    aciklama: { en: 'Convert AVI videos to MKV format.' },
    populer: false,
  },
  {
    slug: 'avi-to-flv',
    from: 'AVI',
    to: 'FLV',
    fromExt: 'avi',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → FLV Converter' },
    aciklama: { en: 'Convert AVI videos to FLV format.' },
    populer: false,
  },
  {
    slug: 'avi-to-wmv',
    from: 'AVI',
    to: 'WMV',
    fromExt: 'avi',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → WMV Converter' },
    aciklama: { en: 'Convert AVI videos to WMV format.' },
    populer: false,
  },
  {
    slug: 'avi-to-gif',
    from: 'AVI',
    to: 'GIF',
    fromExt: 'avi',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → GIF Converter' },
    aciklama: { en: 'Convert AVI videos to animated GIF files.' },
    populer: false,
  },
  {
    slug: 'mov-to-webm',
    from: 'MOV',
    to: 'WebM',
    fromExt: 'mov',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → WebM Converter' },
    aciklama: { en: 'Convert MOV videos to open-source WebM format.' },
    populer: false,
  },
  {
    slug: 'mov-to-avi',
    from: 'MOV',
    to: 'AVI',
    fromExt: 'mov',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → AVI Converter' },
    aciklama: { en: 'Convert MOV videos to AVI format.' },
    populer: false,
  },
  {
    slug: 'mov-to-mkv',
    from: 'MOV',
    to: 'MKV',
    fromExt: 'mov',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → MKV Converter' },
    aciklama: { en: 'Convert MOV videos to MKV format.' },
    populer: false,
  },
  {
    slug: 'mov-to-flv',
    from: 'MOV',
    to: 'FLV',
    fromExt: 'mov',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → FLV Converter' },
    aciklama: { en: 'Convert MOV videos to FLV format.' },
    populer: false,
  },
  {
    slug: 'mov-to-wmv',
    from: 'MOV',
    to: 'WMV',
    fromExt: 'mov',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → WMV Converter' },
    aciklama: { en: 'Convert MOV videos to WMV format.' },
    populer: false,
  },
  {
    slug: 'mov-to-gif',
    from: 'MOV',
    to: 'GIF',
    fromExt: 'mov',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → GIF Converter' },
    aciklama: { en: 'Convert MOV videos to animated GIF files.' },
    populer: false,
  },
  {
    slug: 'mkv-to-webm',
    from: 'MKV',
    to: 'WebM',
    fromExt: 'mkv',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → WebM Converter' },
    aciklama: { en: 'Convert MKV videos to open-source WebM format.' },
    populer: false,
  },
  {
    slug: 'mkv-to-avi',
    from: 'MKV',
    to: 'AVI',
    fromExt: 'mkv',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → AVI Converter' },
    aciklama: { en: 'Convert MKV videos to AVI format.' },
    populer: false,
  },
  {
    slug: 'mkv-to-mov',
    from: 'MKV',
    to: 'MOV',
    fromExt: 'mkv',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → MOV Converter' },
    aciklama: { en: 'Convert MKV videos to Apple MOV format.' },
    populer: false,
  },
  {
    slug: 'mkv-to-flv',
    from: 'MKV',
    to: 'FLV',
    fromExt: 'mkv',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → FLV Converter' },
    aciklama: { en: 'Convert MKV videos to FLV format.' },
    populer: false,
  },
  {
    slug: 'mkv-to-wmv',
    from: 'MKV',
    to: 'WMV',
    fromExt: 'mkv',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → WMV Converter' },
    aciklama: { en: 'Convert MKV videos to WMV format.' },
    populer: false,
  },
  {
    slug: 'mkv-to-gif',
    from: 'MKV',
    to: 'GIF',
    fromExt: 'mkv',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → GIF Converter' },
    aciklama: { en: 'Convert MKV videos to animated GIF files.' },
    populer: false,
  },
  {
    slug: 'flv-to-mp4',
    from: 'FLV',
    to: 'MP4',
    fromExt: 'flv',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MP4 Converter' },
    aciklama: { en: 'Convert FLV videos to compatible MP4 format.' },
    populer: false,
  },
  {
    slug: 'flv-to-webm',
    from: 'FLV',
    to: 'WebM',
    fromExt: 'flv',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → WebM Converter' },
    aciklama: { en: 'Convert FLV videos to open-source WebM format.' },
    populer: false,
  },
  {
    slug: 'flv-to-avi',
    from: 'FLV',
    to: 'AVI',
    fromExt: 'flv',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → AVI Converter' },
    aciklama: { en: 'Convert FLV videos to AVI format.' },
    populer: false,
  },
  {
    slug: 'flv-to-mov',
    from: 'FLV',
    to: 'MOV',
    fromExt: 'flv',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MOV Converter' },
    aciklama: { en: 'Convert FLV videos to Apple MOV format.' },
    populer: false,
  },
  {
    slug: 'flv-to-mkv',
    from: 'FLV',
    to: 'MKV',
    fromExt: 'flv',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MKV Converter' },
    aciklama: { en: 'Convert FLV videos to MKV format.' },
    populer: false,
  },
  {
    slug: 'flv-to-wmv',
    from: 'FLV',
    to: 'WMV',
    fromExt: 'flv',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → WMV Converter' },
    aciklama: { en: 'Convert FLV videos to WMV format.' },
    populer: false,
  },
  {
    slug: 'flv-to-gif',
    from: 'FLV',
    to: 'GIF',
    fromExt: 'flv',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → GIF Converter' },
    aciklama: { en: 'Convert FLV videos to animated GIF files.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mp4',
    from: 'WMV',
    to: 'MP4',
    fromExt: 'wmv',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MP4 Converter' },
    aciklama: { en: 'Convert WMV videos to compatible MP4 format.' },
    populer: false,
  },
  {
    slug: 'wmv-to-webm',
    from: 'WMV',
    to: 'WebM',
    fromExt: 'wmv',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → WebM Converter' },
    aciklama: { en: 'Convert WMV videos to open-source WebM format.' },
    populer: false,
  },
  {
    slug: 'wmv-to-avi',
    from: 'WMV',
    to: 'AVI',
    fromExt: 'wmv',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → AVI Converter' },
    aciklama: { en: 'Convert WMV videos to AVI format.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mov',
    from: 'WMV',
    to: 'MOV',
    fromExt: 'wmv',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MOV Converter' },
    aciklama: { en: 'Convert WMV videos to Apple MOV format.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mkv',
    from: 'WMV',
    to: 'MKV',
    fromExt: 'wmv',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MKV Converter' },
    aciklama: { en: 'Convert WMV videos to MKV format.' },
    populer: false,
  },
  {
    slug: 'wmv-to-flv',
    from: 'WMV',
    to: 'FLV',
    fromExt: 'wmv',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → FLV Converter' },
    aciklama: { en: 'Convert WMV videos to FLV format.' },
    populer: false,
  },
  {
    slug: 'wmv-to-gif',
    from: 'WMV',
    to: 'GIF',
    fromExt: 'wmv',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → GIF Converter' },
    aciklama: { en: 'Convert WMV videos to animated GIF files.' },
    populer: false,
  },
  {
    slug: 'gif-to-mp4',
    from: 'GIF',
    to: 'MP4',
    fromExt: 'gif',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → MP4 Converter' },
    aciklama: { en: 'Convert animated GIF files to MP4 format.' },
    populer: false,
  },
  {
    slug: 'gif-to-webm',
    from: 'GIF',
    to: 'WebM',
    fromExt: 'gif',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → WebM Converter' },
    aciklama: { en: 'Convert animated GIF files to WebM format.' },
    populer: false,
  },
  {
    slug: 'gif-to-avi',
    from: 'GIF',
    to: 'AVI',
    fromExt: 'gif',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → AVI Converter' },
    aciklama: { en: 'Convert animated GIF files to AVI format.' },
    populer: false,
  },
  {
    slug: 'gif-to-mov',
    from: 'GIF',
    to: 'MOV',
    fromExt: 'gif',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → MOV Converter' },
    aciklama: { en: 'Convert animated GIF files to Apple MOV format.' },
    populer: false,
  },
  {
    slug: 'gif-to-mkv',
    from: 'GIF',
    to: 'MKV',
    fromExt: 'gif',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → MKV Converter' },
    aciklama: { en: 'Convert animated GIF files to MKV format.' },
    populer: false,
  },
  {
    slug: 'gif-to-flv',
    from: 'GIF',
    to: 'FLV',
    fromExt: 'gif',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → FLV Converter' },
    aciklama: { en: 'Convert animated GIF files to FLV format.' },
    populer: false,
  },
  {
    slug: 'gif-to-wmv',
    from: 'GIF',
    to: 'WMV',
    fromExt: 'gif',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → WMV Converter' },
    aciklama: { en: 'Convert animated GIF files to WMV format.' },
    populer: false,
  },


  // ===== SES =====
  {
    slug: 'mp3-to-wav',
    from: 'MP3',
    to: 'WAV',
    fromExt: 'mp3',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → WAV Converter' },
    aciklama: { en: 'Convert your MP3 files to lossless WAV format.' },
    populer: true,
    ffmpegArgs: ['-acodec', 'pcm_s16le'],
  },
  {
    slug: 'wav-to-mp3',
    from: 'WAV',
    to: 'MP3',
    fromExt: 'wav',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → MP3 Converter' },
    aciklama: { en: 'Compress your large WAV files to small MP3 format.' },
    populer: true,
    ffmpegArgs: ['-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'mp4-to-mp3',
    from: 'MP4',
    to: 'MP3',
    fromExt: 'mp4',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → MP3 Converter' },
    aciklama: { en: 'Extract audio from videos. Save the audio part of your MP4 file as MP3.' },
    populer: true,
    ffmpegArgs: ['-vn', '-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'ogg-to-mp3',
    from: 'OGG',
    to: 'MP3',
    fromExt: 'ogg',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → MP3 Converter' },
    aciklama: { en: 'Convert your OGG audio files to the common MP3 format.' },
    populer: false,
    ffmpegArgs: ['-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'mp3-to-ogg',
    from: 'MP3',
    to: 'OGG',
    fromExt: 'mp3',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → OGG Converter' },
    aciklama: { en: 'Convert your MP3 files to open-source OGG format.' },
    populer: false,
    ffmpegArgs: ['-acodec', 'libvorbis', '-b:a', '192k'],
  },
  {
    slug: 'webm-to-mp3',
    from: 'WebM',
    to: 'MP3',
    fromExt: 'webm',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MP3 Converter' },
    aciklama: { en: 'Extract audio from WebM videos and save it as MP3.' },
    populer: false,
    ffmpegArgs: ['-vn', '-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'flac-to-mp3',
    from: 'FLAC',
    to: 'MP3',
    fromExt: 'flac',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → MP3 Converter' },
    aciklama: { en: 'Convert your lossless FLAC files to MP3 format.' },
    populer: false,
    ffmpegArgs: ['-acodec', 'libmp3lame', '-b:a', '320k'],
  },
  {
    slug: 'mp3-to-aac',
    from: 'MP3',
    to: 'AAC',
    fromExt: 'mp3',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → AAC Converter' },
    aciklama: { en: 'Convert your MP3 files to AAC format.' },
    populer: false,
  },
  {
    slug: 'mp3-to-flac',
    from: 'MP3',
    to: 'FLAC',
    fromExt: 'mp3',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → FLAC Converter' },
    aciklama: { en: 'Convert your MP3 files to lossless FLAC format.' },
    populer: false,
  },
  {
    slug: 'mp3-to-m4a',
    from: 'MP3',
    to: 'M4A',
    fromExt: 'mp3',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → M4A Converter' },
    aciklama: { en: 'Convert your MP3 files to M4A format.' },
    populer: false,
  },
  {
    slug: 'mp3-to-wma',
    from: 'MP3',
    to: 'WMA',
    fromExt: 'mp3',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → WMA Converter' },
    aciklama: { en: 'Convert your MP3 files to WMA format.' },
    populer: false,
  },
  {
    slug: 'mp3-to-opus',
    from: 'MP3',
    to: 'OPUS',
    fromExt: 'mp3',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → OPUS Converter' },
    aciklama: { en: 'Convert your MP3 files to OPUS format.' },
    populer: false,
  },
  {
    slug: 'wav-to-ogg',
    from: 'WAV',
    to: 'OGG',
    fromExt: 'wav',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → OGG Converter' },
    aciklama: { en: 'Convert WAV files to OGG format.' },
    populer: false,
  },
  {
    slug: 'wav-to-aac',
    from: 'WAV',
    to: 'AAC',
    fromExt: 'wav',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → AAC Converter' },
    aciklama: { en: 'Convert WAV files to AAC format.' },
    populer: false,
  },
  {
    slug: 'wav-to-flac',
    from: 'WAV',
    to: 'FLAC',
    fromExt: 'wav',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → FLAC Converter' },
    aciklama: { en: 'Convert WAV files to lossless FLAC format.' },
    populer: false,
  },
  {
    slug: 'wav-to-m4a',
    from: 'WAV',
    to: 'M4A',
    fromExt: 'wav',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → M4A Converter' },
    aciklama: { en: 'Convert WAV files to M4A format.' },
    populer: false,
  },
  {
    slug: 'wav-to-wma',
    from: 'WAV',
    to: 'WMA',
    fromExt: 'wav',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → WMA Converter' },
    aciklama: { en: 'Convert WAV files to WMA format.' },
    populer: false,
  },
  {
    slug: 'wav-to-opus',
    from: 'WAV',
    to: 'OPUS',
    fromExt: 'wav',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → OPUS Converter' },
    aciklama: { en: 'Convert WAV files to OPUS format.' },
    populer: false,
  },
  {
    slug: 'ogg-to-wav',
    from: 'OGG',
    to: 'WAV',
    fromExt: 'ogg',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → WAV Converter' },
    aciklama: { en: 'Convert OGG files to WAV format.' },
    populer: false,
  },
  {
    slug: 'ogg-to-aac',
    from: 'OGG',
    to: 'AAC',
    fromExt: 'ogg',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → AAC Converter' },
    aciklama: { en: 'Convert OGG files to AAC format.' },
    populer: false,
  },
  {
    slug: 'ogg-to-flac',
    from: 'OGG',
    to: 'FLAC',
    fromExt: 'ogg',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → FLAC Converter' },
    aciklama: { en: 'Convert OGG files to lossless FLAC format.' },
    populer: false,
  },
  {
    slug: 'ogg-to-m4a',
    from: 'OGG',
    to: 'M4A',
    fromExt: 'ogg',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → M4A Converter' },
    aciklama: { en: 'Convert OGG files to M4A format.' },
    populer: false,
  },
  {
    slug: 'ogg-to-wma',
    from: 'OGG',
    to: 'WMA',
    fromExt: 'ogg',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → WMA Converter' },
    aciklama: { en: 'Convert OGG files to WMA format.' },
    populer: false,
  },
  {
    slug: 'ogg-to-opus',
    from: 'OGG',
    to: 'OPUS',
    fromExt: 'ogg',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → OPUS Converter' },
    aciklama: { en: 'Convert OGG files to OPUS format.' },
    populer: false,
  },
  {
    slug: 'aac-to-mp3',
    from: 'AAC',
    to: 'MP3',
    fromExt: 'aac',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → MP3 Converter' },
    aciklama: { en: 'Convert AAC files to MP3 format.' },
    populer: false,
  },
  {
    slug: 'aac-to-wav',
    from: 'AAC',
    to: 'WAV',
    fromExt: 'aac',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → WAV Converter' },
    aciklama: { en: 'Convert AAC files to WAV format.' },
    populer: false,
  },
  {
    slug: 'aac-to-ogg',
    from: 'AAC',
    to: 'OGG',
    fromExt: 'aac',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → OGG Converter' },
    aciklama: { en: 'Convert AAC files to OGG format.' },
    populer: false,
  },
  {
    slug: 'aac-to-flac',
    from: 'AAC',
    to: 'FLAC',
    fromExt: 'aac',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → FLAC Converter' },
    aciklama: { en: 'Convert AAC files to lossless FLAC format.' },
    populer: false,
  },
  {
    slug: 'aac-to-m4a',
    from: 'AAC',
    to: 'M4A',
    fromExt: 'aac',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → M4A Converter' },
    aciklama: { en: 'Convert AAC files to M4A format.' },
    populer: false,
  },
  {
    slug: 'aac-to-wma',
    from: 'AAC',
    to: 'WMA',
    fromExt: 'aac',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → WMA Converter' },
    aciklama: { en: 'Convert AAC files to WMA format.' },
    populer: false,
  },
  {
    slug: 'aac-to-opus',
    from: 'AAC',
    to: 'OPUS',
    fromExt: 'aac',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → OPUS Converter' },
    aciklama: { en: 'Convert AAC files to OPUS format.' },
    populer: false,
  },
  {
    slug: 'flac-to-wav',
    from: 'FLAC',
    to: 'WAV',
    fromExt: 'flac',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → WAV Converter' },
    aciklama: { en: 'Convert FLAC files to WAV format.' },
    populer: false,
  },
  {
    slug: 'flac-to-ogg',
    from: 'FLAC',
    to: 'OGG',
    fromExt: 'flac',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → OGG Converter' },
    aciklama: { en: 'Convert FLAC files to OGG format.' },
    populer: false,
  },
  {
    slug: 'flac-to-aac',
    from: 'FLAC',
    to: 'AAC',
    fromExt: 'flac',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → AAC Converter' },
    aciklama: { en: 'Convert FLAC files to AAC format.' },
    populer: false,
  },
  {
    slug: 'flac-to-m4a',
    from: 'FLAC',
    to: 'M4A',
    fromExt: 'flac',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → M4A Converter' },
    aciklama: { en: 'Convert FLAC files to M4A format.' },
    populer: false,
  },
  {
    slug: 'flac-to-wma',
    from: 'FLAC',
    to: 'WMA',
    fromExt: 'flac',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → WMA Converter' },
    aciklama: { en: 'Convert FLAC files to WMA format.' },
    populer: false,
  },
  {
    slug: 'flac-to-opus',
    from: 'FLAC',
    to: 'OPUS',
    fromExt: 'flac',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → OPUS Converter' },
    aciklama: { en: 'Convert FLAC files to OPUS format.' },
    populer: false,
  },
  {
    slug: 'm4a-to-mp3',
    from: 'M4A',
    to: 'MP3',
    fromExt: 'm4a',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → MP3 Converter' },
    aciklama: { en: 'Convert M4A files to MP3 format.' },
    populer: false,
  },
  {
    slug: 'm4a-to-wav',
    from: 'M4A',
    to: 'WAV',
    fromExt: 'm4a',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → WAV Converter' },
    aciklama: { en: 'Convert M4A files to WAV format.' },
    populer: false,
  },
  {
    slug: 'm4a-to-ogg',
    from: 'M4A',
    to: 'OGG',
    fromExt: 'm4a',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → OGG Converter' },
    aciklama: { en: 'Convert M4A files to OGG format.' },
    populer: false,
  },
  {
    slug: 'm4a-to-aac',
    from: 'M4A',
    to: 'AAC',
    fromExt: 'm4a',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → AAC Converter' },
    aciklama: { en: 'Convert M4A files to AAC format.' },
    populer: false,
  },
  {
    slug: 'm4a-to-flac',
    from: 'M4A',
    to: 'FLAC',
    fromExt: 'm4a',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → FLAC Converter' },
    aciklama: { en: 'Convert M4A files to lossless FLAC format.' },
    populer: false,
  },
  {
    slug: 'm4a-to-wma',
    from: 'M4A',
    to: 'WMA',
    fromExt: 'm4a',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → WMA Converter' },
    aciklama: { en: 'Convert M4A files to WMA format.' },
    populer: false,
  },
  {
    slug: 'm4a-to-opus',
    from: 'M4A',
    to: 'OPUS',
    fromExt: 'm4a',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → OPUS Converter' },
    aciklama: { en: 'Convert M4A files to OPUS format.' },
    populer: false,
  },
  {
    slug: 'wma-to-mp3',
    from: 'WMA',
    to: 'MP3',
    fromExt: 'wma',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → MP3 Converter' },
    aciklama: { en: 'Convert WMA files to MP3 format.' },
    populer: false,
  },
  {
    slug: 'wma-to-wav',
    from: 'WMA',
    to: 'WAV',
    fromExt: 'wma',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → WAV Converter' },
    aciklama: { en: 'Convert WMA files to WAV format.' },
    populer: false,
  },
  {
    slug: 'wma-to-ogg',
    from: 'WMA',
    to: 'OGG',
    fromExt: 'wma',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → OGG Converter' },
    aciklama: { en: 'Convert WMA files to OGG format.' },
    populer: false,
  },
  {
    slug: 'wma-to-aac',
    from: 'WMA',
    to: 'AAC',
    fromExt: 'wma',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → AAC Converter' },
    aciklama: { en: 'Convert WMA files to AAC format.' },
    populer: false,
  },
  {
    slug: 'wma-to-flac',
    from: 'WMA',
    to: 'FLAC',
    fromExt: 'wma',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → FLAC Converter' },
    aciklama: { en: 'Convert WMA files to lossless FLAC format.' },
    populer: false,
  },
  {
    slug: 'wma-to-m4a',
    from: 'WMA',
    to: 'M4A',
    fromExt: 'wma',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → M4A Converter' },
    aciklama: { en: 'Convert WMA files to M4A format.' },
    populer: false,
  },
  {
    slug: 'wma-to-opus',
    from: 'WMA',
    to: 'OPUS',
    fromExt: 'wma',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → OPUS Converter' },
    aciklama: { en: 'Convert WMA files to OPUS format.' },
    populer: false,
  },
  {
    slug: 'opus-to-mp3',
    from: 'OPUS',
    to: 'MP3',
    fromExt: 'opus',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → MP3 Converter' },
    aciklama: { en: 'Convert OPUS files to MP3 format.' },
    populer: false,
  },
  {
    slug: 'opus-to-wav',
    from: 'OPUS',
    to: 'WAV',
    fromExt: 'opus',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → WAV Converter' },
    aciklama: { en: 'Convert OPUS files to WAV format.' },
    populer: false,
  },
  {
    slug: 'opus-to-ogg',
    from: 'OPUS',
    to: 'OGG',
    fromExt: 'opus',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → OGG Converter' },
    aciklama: { en: 'Convert OPUS files to OGG format.' },
    populer: false,
  },
  {
    slug: 'opus-to-aac',
    from: 'OPUS',
    to: 'AAC',
    fromExt: 'opus',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → AAC Converter' },
    aciklama: { en: 'Convert OPUS files to AAC format.' },
    populer: false,
  },
  {
    slug: 'opus-to-flac',
    from: 'OPUS',
    to: 'FLAC',
    fromExt: 'opus',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → FLAC Converter' },
    aciklama: { en: 'Convert OPUS files to lossless FLAC format.' },
    populer: false,
  },
  {
    slug: 'opus-to-m4a',
    from: 'OPUS',
    to: 'M4A',
    fromExt: 'opus',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → M4A Converter' },
    aciklama: { en: 'Convert OPUS files to M4A format.' },
    populer: false,
  },
  {
    slug: 'opus-to-wma',
    from: 'OPUS',
    to: 'WMA',
    fromExt: 'opus',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → WMA Converter' },
    aciklama: { en: 'Convert OPUS files to WMA format.' },
    populer: false,
  },
  {
    slug: 'mp4-to-wav',
    from: 'MP4',
    to: 'WAV',
    fromExt: 'mp4',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → WAV Converter' },
    aciklama: { en: 'Extract audio from MP4 video and save as WAV.' },
    populer: false,
  },
  {
    slug: 'mp4-to-ogg',
    from: 'MP4',
    to: 'OGG',
    fromExt: 'mp4',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → OGG Converter' },
    aciklama: { en: 'Extract audio from MP4 video and save as OGG.' },
    populer: false,
  },
  {
    slug: 'mp4-to-aac',
    from: 'MP4',
    to: 'AAC',
    fromExt: 'mp4',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → AAC Converter' },
    aciklama: { en: 'Extract audio from MP4 video and save as AAC.' },
    populer: false,
  },
  {
    slug: 'mp4-to-flac',
    from: 'MP4',
    to: 'FLAC',
    fromExt: 'mp4',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → FLAC Converter' },
    aciklama: { en: 'Extract audio from MP4 video and save as FLAC.' },
    populer: false,
  },
  {
    slug: 'mp4-to-m4a',
    from: 'MP4',
    to: 'M4A',
    fromExt: 'mp4',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → M4A Converter' },
    aciklama: { en: 'Extract audio from MP4 video and save as M4A.' },
    populer: false,
  },
  {
    slug: 'mp4-to-opus',
    from: 'MP4',
    to: 'OPUS',
    fromExt: 'mp4',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → OPUS Converter' },
    aciklama: { en: 'Extract audio from MP4 video and save as OPUS.' },
    populer: false,
  },
  {
    slug: 'webm-to-wav',
    from: 'WebM',
    to: 'WAV',
    fromExt: 'webm',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → WAV Converter' },
    aciklama: { en: 'Extract audio from WebM video and save as WAV.' },
    populer: false,
  },
  {
    slug: 'webm-to-ogg',
    from: 'WebM',
    to: 'OGG',
    fromExt: 'webm',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → OGG Converter' },
    aciklama: { en: 'Extract audio from WebM video and save as OGG.' },
    populer: false,
  },
  {
    slug: 'webm-to-aac',
    from: 'WebM',
    to: 'AAC',
    fromExt: 'webm',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → AAC Converter' },
    aciklama: { en: 'Extract audio from WebM video and save as AAC.' },
    populer: false,
  },
  {
    slug: 'mov-to-mp3',
    from: 'MOV',
    to: 'MP3',
    fromExt: 'mov',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → MP3 Converter' },
    aciklama: { en: 'Extract audio from MOV video and save as MP3.' },
    populer: false,
  },
  {
    slug: 'mov-to-wav',
    from: 'MOV',
    to: 'WAV',
    fromExt: 'mov',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → WAV Converter' },
    aciklama: { en: 'Extract audio from MOV video and save as WAV.' },
    populer: false,
  },
  {
    slug: 'mov-to-m4a',
    from: 'MOV',
    to: 'M4A',
    fromExt: 'mov',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → M4A Converter' },
    aciklama: { en: 'Extract audio from MOV video and save as M4A.' },
    populer: false,
  },
  {
    slug: 'avi-to-mp3',
    from: 'AVI',
    to: 'MP3',
    fromExt: 'avi',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MP3 Converter' },
    aciklama: { en: 'Extract audio from AVI video and save as MP3.' },
    populer: false,
  },
  {
    slug: 'avi-to-wav',
    from: 'AVI',
    to: 'WAV',
    fromExt: 'avi',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → WAV Converter' },
    aciklama: { en: 'Extract audio from AVI video and save as WAV.' },
    populer: false,
  },
  {
    slug: 'mkv-to-mp3',
    from: 'MKV',
    to: 'MP3',
    fromExt: 'mkv',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → MP3 Converter' },
    aciklama: { en: 'Extract audio from MKV video and save as MP3.' },
    populer: false,
  },
  {
    slug: 'mkv-to-wav',
    from: 'MKV',
    to: 'WAV',
    fromExt: 'mkv',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → WAV Converter' },
    aciklama: { en: 'Extract audio from MKV video and save as WAV.' },
    populer: false,
  },
  {
    slug: 'mkv-to-flac',
    from: 'MKV',
    to: 'FLAC',
    fromExt: 'mkv',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → FLAC Converter' },
    aciklama: { en: 'Extract audio from MKV video and save as FLAC.' },
    populer: false,
  },
  {
    slug: 'flv-to-mp3',
    from: 'FLV',
    to: 'MP3',
    fromExt: 'flv',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MP3 Converter' },
    aciklama: { en: 'Extract audio from FLV video and save as MP3.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mp3',
    from: 'WMV',
    to: 'MP3',
    fromExt: 'wmv',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MP3 Converter' },
    aciklama: { en: 'Extract audio from WMV video and save as MP3.' },
    populer: false,
  },


  {
    slug: 'mp3-to-txt',
    from: 'MP3',
    to: 'TXT',
    fromExt: 'mp3',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'MP3 → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your MP3 audio files to text using AI directly in your browser.' },
    populer: true,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },
  {
    slug: 'wav-to-txt',
    from: 'WAV',
    to: 'TXT',
    fromExt: 'wav',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'WAV → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your WAV audio files to text using AI directly in your browser.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },
  {
    slug: 'ogg-to-txt',
    from: 'OGG',
    to: 'TXT',
    fromExt: 'ogg',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'OGG → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your OGG audio files to text using AI.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },
  {
    slug: 'm4a-to-txt',
    from: 'M4A',
    to: 'TXT',
    fromExt: 'm4a',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'M4A → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your M4A audio files to text using AI.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },
  {
    slug: 'aac-to-txt',
    from: 'AAC',
    to: 'TXT',
    fromExt: 'aac',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'AAC → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your AAC audio files to text using AI.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },
  {
    slug: 'flac-to-txt',
    from: 'FLAC',
    to: 'TXT',
    fromExt: 'flac',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'FLAC → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your FLAC audio files to text using AI.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },
  {
    slug: 'opus-to-txt',
    from: 'OPUS',
    to: 'TXT',
    fromExt: 'opus',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'OPUS → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your OPUS audio files to text using AI.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },
  {
    slug: 'wma-to-txt',
    from: 'WMA',
    to: 'TXT',
    fromExt: 'wma',
    toExt: 'txt',
    kategori: 'desifre',
    converter: 'whisper',
    baslik: { en: 'WMA → TXT (Speech to Text)' },
    aciklama: { en: 'Transcribe your WMA audio files to text using AI.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language' },
        type: 'select',
        default: 'auto',
        options: WHISPER_LANGUAGES
      }
    ]
  },


  // ===== BELGE =====
  {
    slug: 'images-to-pdf',
    from: 'Görseller',
    to: 'PDF',
    fromExt: 'jpg',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'Convert Images to PDF' },
    aciklama: { en: 'Combine your JPG or PNG images into a single PDF file.' },
    populer: true,
    cokluDosya: true,
  },
  {
    slug: 'pdf-to-png',
    from: 'PDF',
    to: 'PNG',
    fromExt: 'pdf',
    toExt: 'png',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'PDF → PNG Converter' },
    aciklama: { en: 'Convert your PDF pages to separate PNG images.' },
    populer: false,
  },
  {
    slug: 'pdf-to-jpg',
    from: 'PDF',
    to: 'JPG',
    fromExt: 'pdf',
    toExt: 'jpg',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'PDF → JPG Converter' },
    aciklama: { en: 'Convert your PDF pages to separate JPG images.' },
    populer: true,
  },
  {
    slug: 'pdf-to-docx',
    from: 'PDF',
    to: 'DOCX',
    fromExt: 'pdf',
    toExt: 'docx',
    kategori: 'belge',
    converter: 'pdf-lib', // Using pdf-lib for the icon/category tracking implicitly, but we use docx + pdfjs internally. We can use 'pdf-lib' as the type for now to route properly in ConvertPage
    baslik: { en: 'PDF → Word (Text Only)' },
    aciklama: { en: 'Extract text from PDF and convert it to a DOCX file. Images and complex layouts are not preserved.' },
    populer: true,
  },
  {
    slug: 'pdf-to-ocr-pdf',
    from: 'PDF',
    to: 'OCR PDF',
    fromExt: 'pdf',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'tesseract',
    baslik: { en: 'PDF → OCR PDF (Searchable)' },
    aciklama: { en: 'Turn a scanned or image-based PDF into a searchable, selectable PDF using on-device OCR. No file ever leaves your browser.' },
    populer: true,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Document Language' },
        type: 'select',
        default: 'tur+eng',
        options: OCR_LANGUAGES,
      },
    ],
  },
  {
    slug: 'merge-pdf',
    from: 'PDF',
    to: 'PDF',
    fromExt: 'pdf',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'PDF Merger' },
    aciklama: { en: 'Merge multiple PDF files into a single PDF.' },
    populer: true,
    cokluDosya: true,
  },
  {
    slug: 'split-pdf',
    from: 'PDF',
    to: 'PDF',
    fromExt: 'pdf',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'PDF Splitter' },
    aciklama: { en: 'Split your PDF file into separate pages.' },
    populer: false,
  },
  {
    slug: 'text-to-pdf',
    from: 'TXT',
    to: 'PDF',
    fromExt: 'txt',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'Text → PDF Converter' },
    aciklama: { en: 'Convert your text files to professional PDF documents.' },
    populer: false,
  },
  {
    slug: 'docx-to-html',
    from: 'DOCX',
    to: 'HTML',
    fromExt: 'docx',
    toExt: 'html',
    kategori: 'belge',
    converter: 'mammoth',
    baslik: { en: 'DOCX → HTML Converter' },
    aciklama: { en: 'Convert your Word documents to clean HTML code.' },
    populer: false,
  },
  {
    slug: 'excel-to-csv',
    from: 'Excel',
    to: 'CSV',
    fromExt: 'xlsx',
    toExt: 'csv',
    kategori: 'belge',
    converter: 'sheetjs',
    baslik: { en: 'Excel → CSV Converter' },
    aciklama: { en: 'Convert your Excel spreadsheets to CSV format.' },
    populer: false,
  },
  {
    slug: 'csv-to-excel',
    from: 'CSV',
    to: 'Excel',
    fromExt: 'csv',
    toExt: 'xlsx',
    kategori: 'belge',
    converter: 'sheetjs',
    baslik: { en: 'CSV → Excel Converter' },
    aciklama: { en: 'Convert your CSV files to Excel format.' },
    populer: false,
  },
  {
    slug: 'docx-to-pdf',
    from: 'DOCX',
    to: 'PDF',
    fromExt: 'docx',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'DOCX → PDF Converter' },
    aciklama: { en: 'Convert Word document (.docx) to PDF format.' },
    populer: true,
  },
  {
    slug: 'html-to-pdf',
    from: 'HTML',
    to: 'PDF',
    fromExt: 'html',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'HTML → PDF Converter' },
    aciklama: { en: 'Convert HTML files to PDF format.' },
    populer: false,
  },


  // ===== ARŞİV =====
  {
    slug: 'files-to-zip',
    from: 'Dosyalar',
    to: 'ZIP',
    fromExt: '*',
    toExt: 'zip',
    kategori: 'arsiv',
    converter: 'jszip',
    baslik: { en: 'Zip Files' },
    aciklama: { en: 'Compress multiple files into a single ZIP archive.' },
    populer: false,
    cokluDosya: true,
  },
  {
    slug: 'extract-zip',
    from: 'ZIP',
    to: 'Dosyalar',
    fromExt: 'zip',
    toExt: '*',
    kategori: 'arsiv',
    converter: 'jszip',
    baslik: { en: 'Extract ZIP' },
    aciklama: { en: 'Extract ZIP archives and access your files.' },
    populer: false,
  },

  // ===== ALTYAZI =====
  {
    slug: 'srt-to-vtt',
    from: 'SRT',
    to: 'VTT',
    fromExt: 'srt',
    toExt: 'vtt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SRT → VTT Converter' },
    aciklama: { en: 'Convert your SRT subtitle files to HTML5-compatible WebVTT (VTT) format.' },
    populer: true,
  },
  {
    slug: 'vtt-to-srt',
    from: 'VTT',
    to: 'SRT',
    fromExt: 'vtt',
    toExt: 'srt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'VTT → SRT Converter' },
    aciklama: { en: 'Convert your VTT subtitles to the most common format, SRT.' },
    populer: true,
  },
  {
    slug: 'srt-to-ass',
    from: 'SRT',
    to: 'ASS',
    fromExt: 'srt',
    toExt: 'ass',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SRT → ASS Converter' },
    aciklama: { en: 'Convert your SRT files to ASS format with advanced styling support.' },
    populer: false,
  },
  {
    slug: 'ass-to-srt',
    from: 'ASS',
    to: 'SRT',
    fromExt: 'ass',
    toExt: 'srt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'ASS → SRT Converter' },
    aciklama: { en: 'Convert your ASS files to standard SRT format.' },
    populer: false,
  },
  {
    slug: 'sub-to-srt',
    from: 'SUB',
    to: 'SRT',
    fromExt: 'sub',
    toExt: 'srt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SUB → SRT Converter' },
    aciklama: { en: 'Convert your old SUB subtitles to the common SRT format.' },
    populer: false,
  },
  {
    slug: 'srt-to-sub',
    from: 'SRT',
    to: 'SUB',
    fromExt: 'srt',
    toExt: 'sub',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SRT → SUB Converter' },
    aciklama: { en: 'Convert your SRT subtitles to SUB format.' },
    populer: false,
  },
  {
    slug: 'vtt-to-ass',
    from: 'VTT',
    to: 'ASS',
    fromExt: 'vtt',
    toExt: 'ass',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'VTT → ASS Converter' },
    aciklama: { en: 'Convert your VTT subtitles to ASS format.' },
    populer: false,
  },
  {
    slug: 'vtt-to-sub',
    from: 'VTT',
    to: 'SUB',
    fromExt: 'vtt',
    toExt: 'sub',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'VTT → SUB Converter' },
    aciklama: { en: 'Convert your VTT subtitles to SUB format.' },
    populer: false,
  },
  {
    slug: 'ass-to-vtt',
    from: 'ASS',
    to: 'VTT',
    fromExt: 'ass',
    toExt: 'vtt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'ASS → VTT Converter' },
    aciklama: { en: 'Convert your ASS subtitles to WebVTT (VTT) format.' },
    populer: false,
  },
  {
    slug: 'ass-to-sub',
    from: 'ASS',
    to: 'SUB',
    fromExt: 'ass',
    toExt: 'sub',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'ASS → SUB Converter' },
    aciklama: { en: 'Convert your ASS subtitles to SUB format.' },
    populer: false,
  },
  {
    slug: 'sub-to-vtt',
    from: 'SUB',
    to: 'VTT',
    fromExt: 'sub',
    toExt: 'vtt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SUB → VTT Converter' },
    aciklama: { en: 'Convert your SUB subtitles to WebVTT (VTT) format.' },
    populer: false,
  },
  {
    slug: 'sub-to-ass',
    from: 'SUB',
    to: 'ASS',
    fromExt: 'sub',
    toExt: 'ass',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SUB → ASS Converter' },
    aciklama: { en: 'Convert your SUB subtitles to ASS format.' },
    populer: false,
  },

];

// Yardımcı fonksiyonlar
export function getDonusumBySlug(slug: string): DonusumCift | undefined {
  return DONUSUM_DATA.find((d) => d.slug === slug);
}

export function getDonusumlerByKategori(kategori: KategoriSlug): DonusumCift[] {
  return DONUSUM_DATA.filter((d) => d.kategori === kategori);
}

export function getKategoriBySlug(slug: string): Kategori | undefined {
  return KATEGORILER.find((k) => k.slug === slug);
}

export function getPopulerDonusumler(): DonusumCift[] {
  return DONUSUM_DATA.filter((d) => d.populer);
}

export function getIlgiliDonusumler(current: DonusumCift, limit = 6): DonusumCift[] {
  return DONUSUM_DATA.filter(
    (d) =>
      d.slug !== current.slug &&
      (d.kategori === current.kategori ||
        d.fromExt === current.fromExt ||
        d.toExt === current.toExt)
  ).slice(0, limit);
}

// Format renkleri
export function getFormatRenk(format: string): string {
  const map: Record<string, string> = {
    JPG: 'var(--r)',
    JPEG: 'var(--r)',
    PNG: 'var(--b)',
    WebP: 'var(--g)',
    HEIC: 'var(--p)',
    SVG: 'var(--o)',
    BMP: 'var(--y)',
    GIF: 'var(--o)',
    MP4: 'var(--r)',
    WebM: 'var(--g)',
    AVI: 'var(--y)',
    MOV: 'var(--p)',
    MKV: 'var(--b)',
    FLV: 'var(--y)',
    WMV: 'var(--p)',
    MP3: 'var(--o)',
    WAV: 'var(--b)',
    OGG: 'var(--g)',
    FLAC: 'var(--p)',
    AAC: 'var(--y)',
    WMA: 'var(--muted)',
    OPUS: 'var(--g)',
    PDF: 'var(--r)',
    DOCX: 'var(--b)',
    HTML: 'var(--o)',
    TXT: 'var(--muted)',
    M4A: 'var(--b)',

    CSV: 'var(--g)',
    Excel: 'var(--g)',
    XLSX: 'var(--g)',
    ZIP: 'var(--y)',
    Görseller: 'var(--p)',
    Dosyalar: 'var(--b)',
    SRT: 'var(--r)',
    VTT: 'var(--g)',
    ASS: 'var(--p)',
    SUB: 'var(--y)',
  };
  return map[format] || 'var(--muted)';
}
