// lib/donusum-data.ts
// Tüm dönüşüm çiftleri ve kategori verileri

export type ConverterType =
  | 'canvas'
  | 'heic2any'
  | 'ffmpeg'
  | 'pdf-lib'
  | 'mammoth'
  | 'sheetjs'
  | 'jszip'
  | 'subsrt'
  | 'whisper';

export interface Secenek {
  id: string;
  label: { en: string; tr: string };
  type: 'range' | 'select' | 'checkbox';
  default: string | number | boolean;
  min?: number;
  max?: number;
  step?: number;
  options?: { value: string; label: string }[];
  unit?: string;
}

export interface DonusumCift {
  slug: string;
  from: string;
  to: string;
  fromExt: string;
  toExt: string;
  kategori: KategoriSlug;
  converter: ConverterType;
  baslik: { en: string; tr: string };
  aciklama: { en: string; tr: string };
  populer: boolean;
  secenekler?: Secenek[];
  cokluDosya?: boolean;
  ffmpegArgs?: string[];
}

export type KategoriSlug = 'goruntu' | 'video' | 'ses' | 'belge' | 'arsiv' | 'altyazi';

export interface Kategori {
  slug: KategoriSlug;
  baslik: { en: string; tr: string };
  aciklama: { en: string; tr: string };
  ikon: string;
  renk: string;
}

export const KATEGORILER: Kategori[] = [
  {
    slug: 'goruntu',
    baslik: { en: 'Image', tr: 'Görüntü' },
    aciklama: { en: 'Convert between JPG, PNG, WebP, SVG, HEIC and more image formats.', tr: 'JPG, PNG, WebP, SVG, HEIC ve daha fazla görüntü formatı arasında dönüştürme yapın.' },
    ikon: '🖼️',
    renk: '#ff4d6d',
  },
  {
    slug: 'video',
    baslik: { en: 'Video', tr: 'Video' },
    aciklama: { en: 'Convert MP4, WebM, AVI, MOV and other video formats.', tr: 'MP4, WebM, AVI, MOV ve diğer video formatlarını dönüştürün.' },
    ikon: '🎬',
    renk: '#ff8c42',
  },
  {
    slug: 'ses',
    baslik: { en: 'Audio', tr: 'Ses' },
    aciklama: { en: 'Convert between MP3, WAV, OGG, AAC and other audio formats.', tr: 'MP3, WAV, OGG, AAC ve diğer ses formatları arasında dönüştürme.' },
    ikon: '🎵',
    renk: '#ffd166',
  },
  {
    slug: 'belge',
    baslik: { en: 'Document', tr: 'Belge' },
    aciklama: { en: 'Convert PDF, DOCX, TXT, CSV and other document formats.', tr: 'PDF, DOCX, TXT, CSV ve diğer belge formatlarını dönüştürün.' },
    ikon: '📄',
    renk: '#06d6a0',
  },
  {
    slug: 'arsiv',
    baslik: { en: 'Archive', tr: 'Arşiv' },
    aciklama: { en: 'Create and extract ZIP archives.', tr: 'ZIP arşivleri oluşturun ve çıkartın.' },
    ikon: '📦',
    renk: '#4d9fff',
  },
  {
    slug: 'altyazi',
    baslik: { en: 'Subtitle', tr: 'Altyazı' },
    aciklama: { en: 'Convert SRT, VTT, SUB subtitle files.', tr: 'SRT, VTT, SUB altyazı dosyalarını dönüştürün.' },
    ikon: '📝',
    renk: '#ffb703',
  },
];

export function getCategoryPath(lang: string, catSlug: string): string {
  if (lang === 'tr') return `/tr/kategori/${catSlug}`;
  const enMap: Record<string, string> = {
    'goruntu': 'image',
    'video': 'video',
    'ses': 'audio',
    'belge': 'document',
    'arsiv': 'archive',
    'altyazi': 'subtitle'
  };
  return `/en/category/${enMap[catSlug] || catSlug}`;
}

export function getDonusumPath(lang: string, slug: string): string {
  const tool = DONUSUM_DATA.find(d => d.slug === slug);
  if (!tool) return `/${lang}/${slug}`; // Fallback if tool not found

  const catPath = getCategoryPath(lang, tool.kategori);
  return `${catPath}/${slug}`;
}

export function getTranslatedPath(pathname: string, currentLang: string, targetLang: string): string {
  if (currentLang === targetLang) return pathname;

  const enMap: Record<string, string> = {
    'goruntu': 'image',
    'video': 'video',
    'ses': 'audio',
    'belge': 'document',
    'arsiv': 'archive',
    'altyazi': 'subtitle'
  };
  
  const trMap: Record<string, string> = Object.entries(enMap).reduce((acc, [k, v]) => ({ ...acc, [v]: k }), {});

  let newPath = pathname;

  if (currentLang === 'tr' && targetLang === 'en') {
    // /tr/kategori/goruntu/jpg-to-png → /en/category/image/jpg-to-png
    // /tr/kategori/goruntu → /en/category/image
    newPath = newPath.replace('/tr/', '/en/');
    newPath = newPath.replace('/kategori/', '/category/');
    for (const [trSlug, enSlug] of Object.entries(enMap)) {
      // Replace category slug segment (not the tool slug at the end)
      newPath = newPath.replace(`/category/${trSlug}`, `/category/${enSlug}`);
    }
  } else if (currentLang === 'en' && targetLang === 'tr') {
    // /en/category/image/jpg-to-png → /tr/kategori/goruntu/jpg-to-png
    // /en/category/image → /tr/kategori/goruntu
    newPath = newPath.replace('/en/', '/tr/');
    newPath = newPath.replace('/category/', '/kategori/');
    for (const [enSlug, trSlug] of Object.entries(trMap)) {
      newPath = newPath.replace(`/kategori/${enSlug}`, `/kategori/${trSlug}`);
    }
  }

  if (newPath === pathname) {
    newPath = pathname.replace(`/${currentLang}`, `/${targetLang}`);
  }

  return newPath;
}

export function getTranslatedFormat(format: string, lang: string): string {
  if (lang === 'tr') return format;
  const enMap: Record<string, string> = {
    'Görseller': 'Images',
    'Dosyalar': 'Files',
  };
  return enMap[format] || format;
}

export const DONUSUM_DATA: DonusumCift[] = [
  // ===== GÖRÜNTÜ =====
  {
    slug: 'jpg-to-png',
    from: 'JPG',
    to: 'PNG',
    fromExt: 'jpg',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → PNG Converter', tr: 'JPG → PNG Dönüştürücü' },
    aciklama: { en: 'Convert your JPG files to PNG format with transparent background support. Lossless quality, entirely in your browser.', tr: 'JPG dosyalarınızı şeffaf arka plan destekli PNG formatına dönüştürün. Kalite kaybı olmadan, tamamen tarayıcıda.' },
    populer: true,
  },
  {
    slug: 'png-to-jpg',
    from: 'PNG',
    to: 'JPG',
    fromExt: 'png',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → JPG Converter', tr: 'PNG → JPG Dönüştürücü' },
    aciklama: { en: 'Convert your PNG files to smaller-sized JPG format. Optimize file size by adjusting the quality.', tr: 'PNG dosyalarınızı küçük boyutlu JPG formatına dönüştürün. Kaliteyi ayarlayarak dosya boyutunu optimize edin.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality', tr: 'Kalite' },
        type: 'range',
        default: 92,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'jpg-to-webp',
    from: 'JPG',
    to: 'WebP',
    fromExt: 'jpg',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → WebP Converter', tr: 'JPG → WebP Dönüştürücü' },
    aciklama: { en: 'Convert your JPG files to modern WebP format. Smaller size, same quality.', tr: 'JPG dosyalarınızı modern WebP formatına dönüştürün. Daha küçük boyut, aynı kalite.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality', tr: 'Kalite' },
        type: 'range',
        default: 85,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'png-to-webp',
    from: 'PNG',
    to: 'WebP',
    fromExt: 'png',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → WebP Converter', tr: 'PNG → WebP Dönüştürücü' },
    aciklama: { en: 'Convert your PNG images to WebP format. Transparency is preserved, size is reduced.', tr: 'PNG görüntülerinizi WebP formatına dönüştürün. Şeffaflık korunur, boyut küçülür.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality', tr: 'Kalite' },
        type: 'range',
        default: 85,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'webp-to-png',
    from: 'WebP',
    to: 'PNG',
    fromExt: 'webp',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → PNG Converter', tr: 'WebP → PNG Dönüştürücü' },
    aciklama: { en: 'Convert your WebP images to the common PNG format.', tr: 'WebP görüntülerinizi yaygın PNG formatına dönüştürün.' },
    populer: true,
  },
  {
    slug: 'webp-to-jpg',
    from: 'WebP',
    to: 'JPG',
    fromExt: 'webp',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → JPG Converter', tr: 'WebP → JPG Dönüştürücü' },
    aciklama: { en: 'Convert your WebP images to JPG format.', tr: 'WebP görüntülerinizi JPG formatına dönüştürün.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality', tr: 'Kalite' },
        type: 'range',
        default: 92,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'heic-to-jpg',
    from: 'HEIC',
    to: 'JPG',
    fromExt: 'heic',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'heic2any',
    baslik: { en: 'HEIC → JPG Converter', tr: 'HEIC → JPG Dönüştürücü' },
    aciklama: { en: 'Convert your iPhone HEIC photos to JPG format. Make them viewable everywhere.', tr: 'iPhone HEIC fotoğraflarınızı JPG formatına dönüştürün. Her yerde açılabilir hale getirin.' },
    populer: true,
    secenekler: [
      {
        id: 'quality',
        label: { en: 'Quality', tr: 'Kalite' },
        type: 'range',
        default: 92,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    slug: 'heic-to-png',
    from: 'HEIC',
    to: 'PNG',
    fromExt: 'heic',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'heic2any',
    baslik: { en: 'HEIC → PNG Converter', tr: 'HEIC → PNG Dönüştürücü' },
    aciklama: { en: 'Convert your iPhone HEIC photos to transparent PNG format.', tr: 'iPhone HEIC fotoğraflarınızı şeffaf PNG formatına dönüştürün.' },
    populer: true,
  },
  {
    slug: 'svg-to-png',
    from: 'SVG',
    to: 'PNG',
    fromExt: 'svg',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'SVG → PNG Converter', tr: 'SVG → PNG Dönüştürücü' },
    aciklama: { en: 'Convert your vector SVG files to pixel-based PNG format.', tr: 'Vektör SVG dosyalarınızı piksel tabanlı PNG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'bmp-to-png',
    from: 'BMP',
    to: 'PNG',
    fromExt: 'bmp',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → PNG Converter', tr: 'BMP → PNG Dönüştürücü' },
    aciklama: { en: 'Convert your BMP files to compressed PNG format.', tr: 'BMP dosyalarınızı sıkıştırılmış PNG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-png',
    from: 'GIF',
    to: 'PNG',
    fromExt: 'gif',
    toExt: 'png',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → PNG Converter', tr: 'GIF → PNG Dönüştürücü' },
    aciklama: { en: 'Convert the first frame of your GIF files to PNG format.', tr: 'GIF dosyalarının ilk karesini PNG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'jpg-to-bmp',
    from: 'JPG',
    to: 'BMP',
    fromExt: 'jpg',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → BMP Converter', tr: 'JPG → BMP Dönüştürücü' },
    aciklama: { en: 'Convert your JPG images to BMP format.', tr: 'JPG resimlerinizi BMP formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'jpg-to-gif',
    from: 'JPG',
    to: 'GIF',
    fromExt: 'jpg',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'JPG → GIF Converter', tr: 'JPG → GIF Dönüştürücü' },
    aciklama: { en: 'Convert your JPG images to GIF format (first frame).', tr: 'JPG resimlerinizi GIF formatına (ilk kare) dönüştürün.' },
    populer: false,
  },
  {
    slug: 'png-to-bmp',
    from: 'PNG',
    to: 'BMP',
    fromExt: 'png',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → BMP Converter', tr: 'PNG → BMP Dönüştürücü' },
    aciklama: { en: 'Convert your PNG images to BMP format.', tr: 'PNG resimlerinizi BMP formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'png-to-gif',
    from: 'PNG',
    to: 'GIF',
    fromExt: 'png',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'PNG → GIF Converter', tr: 'PNG → GIF Dönüştürücü' },
    aciklama: { en: 'Convert your PNG images to GIF format.', tr: 'PNG resimlerinizi GIF formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webp-to-bmp',
    from: 'WebP',
    to: 'BMP',
    fromExt: 'webp',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → BMP Converter', tr: 'WebP → BMP Dönüştürücü' },
    aciklama: { en: 'Convert your WebP images to BMP format.', tr: 'WebP resimlerinizi BMP formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webp-to-gif',
    from: 'WebP',
    to: 'GIF',
    fromExt: 'webp',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'WebP → GIF Converter', tr: 'WebP → GIF Dönüştürücü' },
    aciklama: { en: 'Convert your WebP images to GIF format.', tr: 'WebP resimlerinizi GIF formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'heic-to-webp',
    from: 'HEIC',
    to: 'WebP',
    fromExt: 'heic',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'heic2any',
    baslik: { en: 'HEIC → WebP Converter', tr: 'HEIC → WebP Dönüştürücü' },
    aciklama: { en: 'Convert HEIC images to modern WebP format.', tr: 'HEIC resimlerinizi modern WebP formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'svg-to-jpg',
    from: 'SVG',
    to: 'JPG',
    fromExt: 'svg',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'SVG → JPG Converter', tr: 'SVG → JPG Dönüştürücü' },
    aciklama: { en: 'Convert vector SVG files to JPG format.', tr: 'Vektör SVG dosyalarınızı JPG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'svg-to-webp',
    from: 'SVG',
    to: 'WebP',
    fromExt: 'svg',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'SVG → WebP Converter', tr: 'SVG → WebP Dönüştürücü' },
    aciklama: { en: 'Convert vector SVG files to WebP format.', tr: 'Vektör SVG dosyalarınızı WebP formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'bmp-to-jpg',
    from: 'BMP',
    to: 'JPG',
    fromExt: 'bmp',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → JPG Converter', tr: 'BMP → JPG Dönüştürücü' },
    aciklama: { en: 'Convert BMP images to JPG format.', tr: 'BMP resimlerinizi JPG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'bmp-to-webp',
    from: 'BMP',
    to: 'WebP',
    fromExt: 'bmp',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → WebP Converter', tr: 'BMP → WebP Dönüştürücü' },
    aciklama: { en: 'Convert BMP images to WebP format.', tr: 'BMP resimlerinizi WebP formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'bmp-to-gif',
    from: 'BMP',
    to: 'GIF',
    fromExt: 'bmp',
    toExt: 'gif',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'BMP → GIF Converter', tr: 'BMP → GIF Dönüştürücü' },
    aciklama: { en: 'Convert BMP images to GIF format.', tr: 'BMP resimlerinizi GIF formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-jpg',
    from: 'GIF',
    to: 'JPG',
    fromExt: 'gif',
    toExt: 'jpg',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → JPG Converter', tr: 'GIF → JPG Dönüştürücü' },
    aciklama: { en: 'Convert GIF images to JPG format.', tr: 'GIF resimlerinizi JPG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-webp',
    from: 'GIF',
    to: 'WebP',
    fromExt: 'gif',
    toExt: 'webp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → WebP Converter', tr: 'GIF → WebP Dönüştürücü' },
    aciklama: { en: 'Convert GIF images to WebP format.', tr: 'GIF resimlerinizi WebP formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-bmp',
    from: 'GIF',
    to: 'BMP',
    fromExt: 'gif',
    toExt: 'bmp',
    kategori: 'goruntu',
    converter: 'canvas',
    baslik: { en: 'GIF → BMP Converter', tr: 'GIF → BMP Dönüştürücü' },
    aciklama: { en: 'Convert GIF images to BMP format.', tr: 'GIF resimlerinizi BMP formatına dönüştürün.' },
    populer: false,
  },


  // ===== VİDEO =====
  {
    slug: 'mp4-to-webm',
    from: 'MP4',
    to: 'WebM',
    fromExt: 'mp4',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → WebM Converter', tr: 'MP4 → WebM Dönüştürücü' },
    aciklama: { en: 'Convert your MP4 videos to open-source WebM format. Optimized for the web.', tr: 'MP4 videolarınızı açık kaynak WebM formatına dönüştürün. Web için optimize.' },
    populer: true,
    ffmpegArgs: ['-c:v', 'libvpx-vp9', '-crf', '30', '-b:v', '0', '-c:a', 'libopus'],
  },
  {
    slug: 'mp4-to-avi',
    from: 'MP4',
    to: 'AVI',
    fromExt: 'mp4',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → AVI Converter', tr: 'MP4 → AVI Dönüştürücü' },
    aciklama: { en: 'Convert your MP4 videos to AVI format.', tr: 'MP4 videolarınızı AVI formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'mpeg4', '-vtag', 'xvid', '-qscale:v', '3', '-c:a', 'libmp3lame'],
  },
  {
    slug: 'mp4-to-mov',
    from: 'MP4',
    to: 'MOV',
    fromExt: 'mp4',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → MOV Converter', tr: 'MP4 → MOV Dönüştürücü' },
    aciklama: { en: 'Convert your MP4 videos to Apple MOV format.', tr: 'MP4 videolarınızı Apple MOV formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'copy', '-c:a', 'copy'],
  },
  {
    slug: 'mp4-to-mkv',
    from: 'MP4',
    to: 'MKV',
    fromExt: 'mp4',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → MKV Converter', tr: 'MP4 → MKV Dönüştürücü' },
    aciklama: { en: 'Convert your MP4 videos to MKV format.', tr: 'MP4 videolarınızı MKV formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'copy', '-c:a', 'copy'],
  },
  {
    slug: 'webm-to-mp4',
    from: 'WebM',
    to: 'MP4',
    fromExt: 'webm',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MP4 Converter', tr: 'WebM → MP4 Dönüştürücü' },
    aciklama: { en: 'Convert your WebM videos to the common MP4 format.', tr: 'WebM videolarınızı yaygın MP4 formatına dönüştürün.' },
    populer: true,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'avi-to-mp4',
    from: 'AVI',
    to: 'MP4',
    fromExt: 'avi',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MP4 Converter', tr: 'AVI → MP4 Dönüştürücü' },
    aciklama: { en: 'Convert your old AVI videos to modern MP4 format.', tr: 'Eski AVI videolarınızı modern MP4 formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'mov-to-mp4',
    from: 'MOV',
    to: 'MP4',
    fromExt: 'mov',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → MP4 Converter', tr: 'MOV → MP4 Dönüştürücü' },
    aciklama: { en: 'Convert your Apple MOV videos to MP4 format. Play on any device.', tr: 'Apple MOV videolarınızı MP4 formatına dönüştürün. Her cihazda oynatın.' },
    populer: true,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'mp4-to-gif',
    from: 'MP4',
    to: 'GIF',
    fromExt: 'mp4',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → GIF Converter', tr: 'MP4 → GIF Dönüştürücü' },
    aciklama: { en: 'Convert your video clips to animated GIF files.', tr: 'Video kliplerinizi animasyonlu GIF dosyalarına dönüştürün.' },
    populer: true,
    ffmpegArgs: ['-vf', 'fps=15,scale=480:-1:flags=lanczos', '-loop', '0'],
  },
  {
    slug: 'mkv-to-mp4',
    from: 'MKV',
    to: 'MP4',
    fromExt: 'mkv',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → MP4 Converter', tr: 'MKV → MP4 Dönüştürücü' },
    aciklama: { en: 'Convert your MKV videos to compatible MP4 format.', tr: 'MKV videolarınızı uyumlu MP4 formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-c:v', 'libx264', '-preset', 'medium', '-crf', '23', '-c:a', 'aac'],
  },
  {
    slug: 'mp4-to-flv',
    from: 'MP4',
    to: 'FLV',
    fromExt: 'mp4',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → FLV Converter', tr: 'MP4 → FLV Dönüştürücü' },
    aciklama: { en: 'Convert MP4 videos to FLV format.', tr: 'MP4 videolarınızı FLV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mp4-to-wmv',
    from: 'MP4',
    to: 'WMV',
    fromExt: 'mp4',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → WMV Converter', tr: 'MP4 → WMV Dönüştürücü' },
    aciklama: { en: 'Convert MP4 videos to WMV format.', tr: 'MP4 videolarınızı WMV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webm-to-avi',
    from: 'WebM',
    to: 'AVI',
    fromExt: 'webm',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → AVI Converter', tr: 'WebM → AVI Dönüştürücü' },
    aciklama: { en: 'Convert WebM videos to AVI format.', tr: 'WebM videolarınızı AVI formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webm-to-mov',
    from: 'WebM',
    to: 'MOV',
    fromExt: 'webm',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MOV Converter', tr: 'WebM → MOV Dönüştürücü' },
    aciklama: { en: 'Convert WebM videos to Apple MOV format.', tr: 'WebM videolarınızı Apple MOV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webm-to-mkv',
    from: 'WebM',
    to: 'MKV',
    fromExt: 'webm',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MKV Converter', tr: 'WebM → MKV Dönüştürücü' },
    aciklama: { en: 'Convert WebM videos to MKV format.', tr: 'WebM videolarınızı MKV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webm-to-flv',
    from: 'WebM',
    to: 'FLV',
    fromExt: 'webm',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → FLV Converter', tr: 'WebM → FLV Dönüştürücü' },
    aciklama: { en: 'Convert WebM videos to FLV format.', tr: 'WebM videolarınızı FLV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webm-to-wmv',
    from: 'WebM',
    to: 'WMV',
    fromExt: 'webm',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → WMV Converter', tr: 'WebM → WMV Dönüştürücü' },
    aciklama: { en: 'Convert WebM videos to WMV format.', tr: 'WebM videolarınızı WMV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'webm-to-gif',
    from: 'WebM',
    to: 'GIF',
    fromExt: 'webm',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → GIF Converter', tr: 'WebM → GIF Dönüştürücü' },
    aciklama: { en: 'Convert WebM videos to animated GIF files.', tr: 'WebM videolarınızı animasyonlu GIF dosyalarına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'avi-to-webm',
    from: 'AVI',
    to: 'WebM',
    fromExt: 'avi',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → WebM Converter', tr: 'AVI → WebM Dönüştürücü' },
    aciklama: { en: 'Convert AVI videos to open-source WebM format.', tr: 'AVI videolarınızı açık kaynak WebM formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'avi-to-mov',
    from: 'AVI',
    to: 'MOV',
    fromExt: 'avi',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MOV Converter', tr: 'AVI → MOV Dönüştürücü' },
    aciklama: { en: 'Convert AVI videos to Apple MOV format.', tr: 'AVI videolarınızı Apple MOV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'avi-to-mkv',
    from: 'AVI',
    to: 'MKV',
    fromExt: 'avi',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MKV Converter', tr: 'AVI → MKV Dönüştürücü' },
    aciklama: { en: 'Convert AVI videos to MKV format.', tr: 'AVI videolarınızı MKV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'avi-to-flv',
    from: 'AVI',
    to: 'FLV',
    fromExt: 'avi',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → FLV Converter', tr: 'AVI → FLV Dönüştürücü' },
    aciklama: { en: 'Convert AVI videos to FLV format.', tr: 'AVI videolarınızı FLV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'avi-to-wmv',
    from: 'AVI',
    to: 'WMV',
    fromExt: 'avi',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → WMV Converter', tr: 'AVI → WMV Dönüştürücü' },
    aciklama: { en: 'Convert AVI videos to WMV format.', tr: 'AVI videolarınızı WMV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'avi-to-gif',
    from: 'AVI',
    to: 'GIF',
    fromExt: 'avi',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → GIF Converter', tr: 'AVI → GIF Dönüştürücü' },
    aciklama: { en: 'Convert AVI videos to animated GIF files.', tr: 'AVI videolarınızı animasyonlu GIF dosyalarına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mov-to-webm',
    from: 'MOV',
    to: 'WebM',
    fromExt: 'mov',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → WebM Converter', tr: 'MOV → WebM Dönüştürücü' },
    aciklama: { en: 'Convert MOV videos to open-source WebM format.', tr: 'MOV videolarınızı açık kaynak WebM formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mov-to-avi',
    from: 'MOV',
    to: 'AVI',
    fromExt: 'mov',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → AVI Converter', tr: 'MOV → AVI Dönüştürücü' },
    aciklama: { en: 'Convert MOV videos to AVI format.', tr: 'MOV videolarınızı AVI formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mov-to-mkv',
    from: 'MOV',
    to: 'MKV',
    fromExt: 'mov',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → MKV Converter', tr: 'MOV → MKV Dönüştürücü' },
    aciklama: { en: 'Convert MOV videos to MKV format.', tr: 'MOV videolarınızı MKV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mov-to-flv',
    from: 'MOV',
    to: 'FLV',
    fromExt: 'mov',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → FLV Converter', tr: 'MOV → FLV Dönüştürücü' },
    aciklama: { en: 'Convert MOV videos to FLV format.', tr: 'MOV videolarınızı FLV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mov-to-wmv',
    from: 'MOV',
    to: 'WMV',
    fromExt: 'mov',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → WMV Converter', tr: 'MOV → WMV Dönüştürücü' },
    aciklama: { en: 'Convert MOV videos to WMV format.', tr: 'MOV videolarınızı WMV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mov-to-gif',
    from: 'MOV',
    to: 'GIF',
    fromExt: 'mov',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → GIF Converter', tr: 'MOV → GIF Dönüştürücü' },
    aciklama: { en: 'Convert MOV videos to animated GIF files.', tr: 'MOV videolarınızı animasyonlu GIF dosyalarına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mkv-to-webm',
    from: 'MKV',
    to: 'WebM',
    fromExt: 'mkv',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → WebM Converter', tr: 'MKV → WebM Dönüştürücü' },
    aciklama: { en: 'Convert MKV videos to open-source WebM format.', tr: 'MKV videolarınızı açık kaynak WebM formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mkv-to-avi',
    from: 'MKV',
    to: 'AVI',
    fromExt: 'mkv',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → AVI Converter', tr: 'MKV → AVI Dönüştürücü' },
    aciklama: { en: 'Convert MKV videos to AVI format.', tr: 'MKV videolarınızı AVI formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mkv-to-mov',
    from: 'MKV',
    to: 'MOV',
    fromExt: 'mkv',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → MOV Converter', tr: 'MKV → MOV Dönüştürücü' },
    aciklama: { en: 'Convert MKV videos to Apple MOV format.', tr: 'MKV videolarınızı Apple MOV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mkv-to-flv',
    from: 'MKV',
    to: 'FLV',
    fromExt: 'mkv',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → FLV Converter', tr: 'MKV → FLV Dönüştürücü' },
    aciklama: { en: 'Convert MKV videos to FLV format.', tr: 'MKV videolarınızı FLV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mkv-to-wmv',
    from: 'MKV',
    to: 'WMV',
    fromExt: 'mkv',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → WMV Converter', tr: 'MKV → WMV Dönüştürücü' },
    aciklama: { en: 'Convert MKV videos to WMV format.', tr: 'MKV videolarınızı WMV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mkv-to-gif',
    from: 'MKV',
    to: 'GIF',
    fromExt: 'mkv',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → GIF Converter', tr: 'MKV → GIF Dönüştürücü' },
    aciklama: { en: 'Convert MKV videos to animated GIF files.', tr: 'MKV videolarınızı animasyonlu GIF dosyalarına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flv-to-mp4',
    from: 'FLV',
    to: 'MP4',
    fromExt: 'flv',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MP4 Converter', tr: 'FLV → MP4 Dönüştürücü' },
    aciklama: { en: 'Convert FLV videos to compatible MP4 format.', tr: 'FLV videolarınızı uyumlu MP4 formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flv-to-webm',
    from: 'FLV',
    to: 'WebM',
    fromExt: 'flv',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → WebM Converter', tr: 'FLV → WebM Dönüştürücü' },
    aciklama: { en: 'Convert FLV videos to open-source WebM format.', tr: 'FLV videolarınızı açık kaynak WebM formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flv-to-avi',
    from: 'FLV',
    to: 'AVI',
    fromExt: 'flv',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → AVI Converter', tr: 'FLV → AVI Dönüştürücü' },
    aciklama: { en: 'Convert FLV videos to AVI format.', tr: 'FLV videolarınızı AVI formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flv-to-mov',
    from: 'FLV',
    to: 'MOV',
    fromExt: 'flv',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MOV Converter', tr: 'FLV → MOV Dönüştürücü' },
    aciklama: { en: 'Convert FLV videos to Apple MOV format.', tr: 'FLV videolarınızı Apple MOV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flv-to-mkv',
    from: 'FLV',
    to: 'MKV',
    fromExt: 'flv',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MKV Converter', tr: 'FLV → MKV Dönüştürücü' },
    aciklama: { en: 'Convert FLV videos to MKV format.', tr: 'FLV videolarınızı MKV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flv-to-wmv',
    from: 'FLV',
    to: 'WMV',
    fromExt: 'flv',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → WMV Converter', tr: 'FLV → WMV Dönüştürücü' },
    aciklama: { en: 'Convert FLV videos to WMV format.', tr: 'FLV videolarınızı WMV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flv-to-gif',
    from: 'FLV',
    to: 'GIF',
    fromExt: 'flv',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → GIF Converter', tr: 'FLV → GIF Dönüştürücü' },
    aciklama: { en: 'Convert FLV videos to animated GIF files.', tr: 'FLV videolarınızı animasyonlu GIF dosyalarına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mp4',
    from: 'WMV',
    to: 'MP4',
    fromExt: 'wmv',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MP4 Converter', tr: 'WMV → MP4 Dönüştürücü' },
    aciklama: { en: 'Convert WMV videos to compatible MP4 format.', tr: 'WMV videolarınızı uyumlu MP4 formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wmv-to-webm',
    from: 'WMV',
    to: 'WebM',
    fromExt: 'wmv',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → WebM Converter', tr: 'WMV → WebM Dönüştürücü' },
    aciklama: { en: 'Convert WMV videos to open-source WebM format.', tr: 'WMV videolarınızı açık kaynak WebM formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wmv-to-avi',
    from: 'WMV',
    to: 'AVI',
    fromExt: 'wmv',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → AVI Converter', tr: 'WMV → AVI Dönüştürücü' },
    aciklama: { en: 'Convert WMV videos to AVI format.', tr: 'WMV videolarınızı AVI formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mov',
    from: 'WMV',
    to: 'MOV',
    fromExt: 'wmv',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MOV Converter', tr: 'WMV → MOV Dönüştürücü' },
    aciklama: { en: 'Convert WMV videos to Apple MOV format.', tr: 'WMV videolarınızı Apple MOV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mkv',
    from: 'WMV',
    to: 'MKV',
    fromExt: 'wmv',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MKV Converter', tr: 'WMV → MKV Dönüştürücü' },
    aciklama: { en: 'Convert WMV videos to MKV format.', tr: 'WMV videolarınızı MKV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wmv-to-flv',
    from: 'WMV',
    to: 'FLV',
    fromExt: 'wmv',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → FLV Converter', tr: 'WMV → FLV Dönüştürücü' },
    aciklama: { en: 'Convert WMV videos to FLV format.', tr: 'WMV videolarınızı FLV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wmv-to-gif',
    from: 'WMV',
    to: 'GIF',
    fromExt: 'wmv',
    toExt: 'gif',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → GIF Converter', tr: 'WMV → GIF Dönüştürücü' },
    aciklama: { en: 'Convert WMV videos to animated GIF files.', tr: 'WMV videolarınızı animasyonlu GIF dosyalarına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-mp4',
    from: 'GIF',
    to: 'MP4',
    fromExt: 'gif',
    toExt: 'mp4',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → MP4 Converter', tr: 'GIF → MP4 Dönüştürücü' },
    aciklama: { en: 'Convert animated GIF files to MP4 format.', tr: 'Animasyonlu GIF dosyalarınızı MP4 formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-webm',
    from: 'GIF',
    to: 'WebM',
    fromExt: 'gif',
    toExt: 'webm',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → WebM Converter', tr: 'GIF → WebM Dönüştürücü' },
    aciklama: { en: 'Convert animated GIF files to WebM format.', tr: 'Animasyonlu GIF dosyalarınızı WebM formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-avi',
    from: 'GIF',
    to: 'AVI',
    fromExt: 'gif',
    toExt: 'avi',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → AVI Converter', tr: 'GIF → AVI Dönüştürücü' },
    aciklama: { en: 'Convert animated GIF files to AVI format.', tr: 'Animasyonlu GIF dosyalarınızı AVI formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-mov',
    from: 'GIF',
    to: 'MOV',
    fromExt: 'gif',
    toExt: 'mov',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → MOV Converter', tr: 'GIF → MOV Dönüştürücü' },
    aciklama: { en: 'Convert animated GIF files to Apple MOV format.', tr: 'Animasyonlu GIF dosyalarınızı Apple MOV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-mkv',
    from: 'GIF',
    to: 'MKV',
    fromExt: 'gif',
    toExt: 'mkv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → MKV Converter', tr: 'GIF → MKV Dönüştürücü' },
    aciklama: { en: 'Convert animated GIF files to MKV format.', tr: 'Animasyonlu GIF dosyalarınızı MKV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-flv',
    from: 'GIF',
    to: 'FLV',
    fromExt: 'gif',
    toExt: 'flv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → FLV Converter', tr: 'GIF → FLV Dönüştürücü' },
    aciklama: { en: 'Convert animated GIF files to FLV format.', tr: 'Animasyonlu GIF dosyalarınızı FLV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'gif-to-wmv',
    from: 'GIF',
    to: 'WMV',
    fromExt: 'gif',
    toExt: 'wmv',
    kategori: 'video',
    converter: 'ffmpeg',
    baslik: { en: 'GIF → WMV Converter', tr: 'GIF → WMV Dönüştürücü' },
    aciklama: { en: 'Convert animated GIF files to WMV format.', tr: 'Animasyonlu GIF dosyalarınızı WMV formatına dönüştürün.' },
    populer: false,
  },


  // ===== SES =====
  {
    slug: 'mp3-to-wav',
    from: 'MP3',
    to: 'WAV',
    fromExt: 'mp3',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → WAV Converter', tr: 'MP3 → WAV Dönüştürücü' },
    aciklama: { en: 'Convert your MP3 files to lossless WAV format.', tr: 'MP3 dosyalarınızı kayıpsız WAV formatına dönüştürün.' },
    populer: true,
    ffmpegArgs: ['-acodec', 'pcm_s16le'],
  },
  {
    slug: 'wav-to-mp3',
    from: 'WAV',
    to: 'MP3',
    fromExt: 'wav',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → MP3 Converter', tr: 'WAV → MP3 Dönüştürücü' },
    aciklama: { en: 'Compress your large WAV files to small MP3 format.', tr: 'Büyük WAV dosyalarınızı küçük MP3 formatına sıkıştırın.' },
    populer: true,
    ffmpegArgs: ['-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'mp4-to-mp3',
    from: 'MP4',
    to: 'MP3',
    fromExt: 'mp4',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → MP3 Converter', tr: 'MP4 → MP3 Dönüştürücü' },
    aciklama: { en: 'Extract audio from videos. Save the audio part of your MP4 file as MP3.', tr: 'Videolardan ses çıkartın. MP4 dosyanızın ses kısmını MP3 olarak kaydedin.' },
    populer: true,
    ffmpegArgs: ['-vn', '-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'ogg-to-mp3',
    from: 'OGG',
    to: 'MP3',
    fromExt: 'ogg',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → MP3 Converter', tr: 'OGG → MP3 Dönüştürücü' },
    aciklama: { en: 'Convert your OGG audio files to the common MP3 format.', tr: 'OGG ses dosyalarınızı yaygın MP3 formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'mp3-to-ogg',
    from: 'MP3',
    to: 'OGG',
    fromExt: 'mp3',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → OGG Converter', tr: 'MP3 → OGG Dönüştürücü' },
    aciklama: { en: 'Convert your MP3 files to open-source OGG format.', tr: 'MP3 dosyalarınızı açık kaynak OGG formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-acodec', 'libvorbis', '-b:a', '192k'],
  },
  {
    slug: 'webm-to-mp3',
    from: 'WebM',
    to: 'MP3',
    fromExt: 'webm',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → MP3 Converter', tr: 'WebM → MP3 Dönüştürücü' },
    aciklama: { en: 'Extract audio from WebM videos and save it as MP3.', tr: 'WebM videolarından ses çıkartın ve MP3 olarak kaydedin.' },
    populer: false,
    ffmpegArgs: ['-vn', '-acodec', 'libmp3lame', '-b:a', '192k'],
  },
  {
    slug: 'flac-to-mp3',
    from: 'FLAC',
    to: 'MP3',
    fromExt: 'flac',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → MP3 Converter', tr: 'FLAC → MP3 Dönüştürücü' },
    aciklama: { en: 'Convert your lossless FLAC files to MP3 format.', tr: 'Kayıpsız FLAC dosyalarınızı MP3 formatına dönüştürün.' },
    populer: false,
    ffmpegArgs: ['-acodec', 'libmp3lame', '-b:a', '320k'],
  },
  {
    slug: 'mp3-to-aac',
    from: 'MP3',
    to: 'AAC',
    fromExt: 'mp3',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → AAC Converter', tr: 'MP3 → AAC Dönüştürücü' },
    aciklama: { en: 'Convert your MP3 files to AAC format.', tr: 'MP3 dosyalarınızı AAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mp3-to-flac',
    from: 'MP3',
    to: 'FLAC',
    fromExt: 'mp3',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → FLAC Converter', tr: 'MP3 → FLAC Dönüştürücü' },
    aciklama: { en: 'Convert your MP3 files to lossless FLAC format.', tr: 'MP3 dosyalarınızı kayıpsız FLAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mp3-to-m4a',
    from: 'MP3',
    to: 'M4A',
    fromExt: 'mp3',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → M4A Converter', tr: 'MP3 → M4A Dönüştürücü' },
    aciklama: { en: 'Convert your MP3 files to M4A format.', tr: 'MP3 dosyalarınızı M4A formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mp3-to-wma',
    from: 'MP3',
    to: 'WMA',
    fromExt: 'mp3',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → WMA Converter', tr: 'MP3 → WMA Dönüştürücü' },
    aciklama: { en: 'Convert your MP3 files to WMA format.', tr: 'MP3 dosyalarınızı WMA formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mp3-to-opus',
    from: 'MP3',
    to: 'OPUS',
    fromExt: 'mp3',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP3 → OPUS Converter', tr: 'MP3 → OPUS Dönüştürücü' },
    aciklama: { en: 'Convert your MP3 files to OPUS format.', tr: 'MP3 dosyalarınızı OPUS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wav-to-ogg',
    from: 'WAV',
    to: 'OGG',
    fromExt: 'wav',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → OGG Converter', tr: 'WAV → OGG Dönüştürücü' },
    aciklama: { en: 'Convert WAV files to OGG format.', tr: 'WAV dosyalarınızı OGG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wav-to-aac',
    from: 'WAV',
    to: 'AAC',
    fromExt: 'wav',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → AAC Converter', tr: 'WAV → AAC Dönüştürücü' },
    aciklama: { en: 'Convert WAV files to AAC format.', tr: 'WAV dosyalarınızı AAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wav-to-flac',
    from: 'WAV',
    to: 'FLAC',
    fromExt: 'wav',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → FLAC Converter', tr: 'WAV → FLAC Dönüştürücü' },
    aciklama: { en: 'Convert WAV files to lossless FLAC format.', tr: 'WAV dosyalarınızı kayıpsız FLAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wav-to-m4a',
    from: 'WAV',
    to: 'M4A',
    fromExt: 'wav',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → M4A Converter', tr: 'WAV → M4A Dönüştürücü' },
    aciklama: { en: 'Convert WAV files to M4A format.', tr: 'WAV dosyalarınızı M4A formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wav-to-wma',
    from: 'WAV',
    to: 'WMA',
    fromExt: 'wav',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → WMA Converter', tr: 'WAV → WMA Dönüştürücü' },
    aciklama: { en: 'Convert WAV files to WMA format.', tr: 'WAV dosyalarınızı WMA formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wav-to-opus',
    from: 'WAV',
    to: 'OPUS',
    fromExt: 'wav',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WAV → OPUS Converter', tr: 'WAV → OPUS Dönüştürücü' },
    aciklama: { en: 'Convert WAV files to OPUS format.', tr: 'WAV dosyalarınızı OPUS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ogg-to-wav',
    from: 'OGG',
    to: 'WAV',
    fromExt: 'ogg',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → WAV Converter', tr: 'OGG → WAV Dönüştürücü' },
    aciklama: { en: 'Convert OGG files to WAV format.', tr: 'OGG dosyalarınızı WAV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ogg-to-aac',
    from: 'OGG',
    to: 'AAC',
    fromExt: 'ogg',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → AAC Converter', tr: 'OGG → AAC Dönüştürücü' },
    aciklama: { en: 'Convert OGG files to AAC format.', tr: 'OGG dosyalarınızı AAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ogg-to-flac',
    from: 'OGG',
    to: 'FLAC',
    fromExt: 'ogg',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → FLAC Converter', tr: 'OGG → FLAC Dönüştürücü' },
    aciklama: { en: 'Convert OGG files to lossless FLAC format.', tr: 'OGG dosyalarınızı kayıpsız FLAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ogg-to-m4a',
    from: 'OGG',
    to: 'M4A',
    fromExt: 'ogg',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → M4A Converter', tr: 'OGG → M4A Dönüştürücü' },
    aciklama: { en: 'Convert OGG files to M4A format.', tr: 'OGG dosyalarınızı M4A formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ogg-to-wma',
    from: 'OGG',
    to: 'WMA',
    fromExt: 'ogg',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → WMA Converter', tr: 'OGG → WMA Dönüştürücü' },
    aciklama: { en: 'Convert OGG files to WMA format.', tr: 'OGG dosyalarınızı WMA formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ogg-to-opus',
    from: 'OGG',
    to: 'OPUS',
    fromExt: 'ogg',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OGG → OPUS Converter', tr: 'OGG → OPUS Dönüştürücü' },
    aciklama: { en: 'Convert OGG files to OPUS format.', tr: 'OGG dosyalarınızı OPUS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'aac-to-mp3',
    from: 'AAC',
    to: 'MP3',
    fromExt: 'aac',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → MP3 Converter', tr: 'AAC → MP3 Dönüştürücü' },
    aciklama: { en: 'Convert AAC files to MP3 format.', tr: 'AAC dosyalarınızı MP3 formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'aac-to-wav',
    from: 'AAC',
    to: 'WAV',
    fromExt: 'aac',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → WAV Converter', tr: 'AAC → WAV Dönüştürücü' },
    aciklama: { en: 'Convert AAC files to WAV format.', tr: 'AAC dosyalarınızı WAV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'aac-to-ogg',
    from: 'AAC',
    to: 'OGG',
    fromExt: 'aac',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → OGG Converter', tr: 'AAC → OGG Dönüştürücü' },
    aciklama: { en: 'Convert AAC files to OGG format.', tr: 'AAC dosyalarınızı OGG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'aac-to-flac',
    from: 'AAC',
    to: 'FLAC',
    fromExt: 'aac',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → FLAC Converter', tr: 'AAC → FLAC Dönüştürücü' },
    aciklama: { en: 'Convert AAC files to lossless FLAC format.', tr: 'AAC dosyalarınızı kayıpsız FLAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'aac-to-m4a',
    from: 'AAC',
    to: 'M4A',
    fromExt: 'aac',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → M4A Converter', tr: 'AAC → M4A Dönüştürücü' },
    aciklama: { en: 'Convert AAC files to M4A format.', tr: 'AAC dosyalarınızı M4A formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'aac-to-wma',
    from: 'AAC',
    to: 'WMA',
    fromExt: 'aac',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → WMA Converter', tr: 'AAC → WMA Dönüştürücü' },
    aciklama: { en: 'Convert AAC files to WMA format.', tr: 'AAC dosyalarınızı WMA formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'aac-to-opus',
    from: 'AAC',
    to: 'OPUS',
    fromExt: 'aac',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AAC → OPUS Converter', tr: 'AAC → OPUS Dönüştürücü' },
    aciklama: { en: 'Convert AAC files to OPUS format.', tr: 'AAC dosyalarınızı OPUS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flac-to-wav',
    from: 'FLAC',
    to: 'WAV',
    fromExt: 'flac',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → WAV Converter', tr: 'FLAC → WAV Dönüştürücü' },
    aciklama: { en: 'Convert FLAC files to WAV format.', tr: 'FLAC dosyalarınızı WAV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flac-to-ogg',
    from: 'FLAC',
    to: 'OGG',
    fromExt: 'flac',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → OGG Converter', tr: 'FLAC → OGG Dönüştürücü' },
    aciklama: { en: 'Convert FLAC files to OGG format.', tr: 'FLAC dosyalarınızı OGG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flac-to-aac',
    from: 'FLAC',
    to: 'AAC',
    fromExt: 'flac',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → AAC Converter', tr: 'FLAC → AAC Dönüştürücü' },
    aciklama: { en: 'Convert FLAC files to AAC format.', tr: 'FLAC dosyalarınızı AAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flac-to-m4a',
    from: 'FLAC',
    to: 'M4A',
    fromExt: 'flac',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → M4A Converter', tr: 'FLAC → M4A Dönüştürücü' },
    aciklama: { en: 'Convert FLAC files to M4A format.', tr: 'FLAC dosyalarınızı M4A formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flac-to-wma',
    from: 'FLAC',
    to: 'WMA',
    fromExt: 'flac',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → WMA Converter', tr: 'FLAC → WMA Dönüştürücü' },
    aciklama: { en: 'Convert FLAC files to WMA format.', tr: 'FLAC dosyalarınızı WMA formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'flac-to-opus',
    from: 'FLAC',
    to: 'OPUS',
    fromExt: 'flac',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLAC → OPUS Converter', tr: 'FLAC → OPUS Dönüştürücü' },
    aciklama: { en: 'Convert FLAC files to OPUS format.', tr: 'FLAC dosyalarınızı OPUS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'm4a-to-mp3',
    from: 'M4A',
    to: 'MP3',
    fromExt: 'm4a',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → MP3 Converter', tr: 'M4A → MP3 Dönüştürücü' },
    aciklama: { en: 'Convert M4A files to MP3 format.', tr: 'M4A dosyalarınızı MP3 formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'm4a-to-wav',
    from: 'M4A',
    to: 'WAV',
    fromExt: 'm4a',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → WAV Converter', tr: 'M4A → WAV Dönüştürücü' },
    aciklama: { en: 'Convert M4A files to WAV format.', tr: 'M4A dosyalarınızı WAV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'm4a-to-ogg',
    from: 'M4A',
    to: 'OGG',
    fromExt: 'm4a',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → OGG Converter', tr: 'M4A → OGG Dönüştürücü' },
    aciklama: { en: 'Convert M4A files to OGG format.', tr: 'M4A dosyalarınızı OGG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'm4a-to-aac',
    from: 'M4A',
    to: 'AAC',
    fromExt: 'm4a',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → AAC Converter', tr: 'M4A → AAC Dönüştürücü' },
    aciklama: { en: 'Convert M4A files to AAC format.', tr: 'M4A dosyalarınızı AAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'm4a-to-flac',
    from: 'M4A',
    to: 'FLAC',
    fromExt: 'm4a',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → FLAC Converter', tr: 'M4A → FLAC Dönüştürücü' },
    aciklama: { en: 'Convert M4A files to lossless FLAC format.', tr: 'M4A dosyalarınızı kayıpsız FLAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'm4a-to-wma',
    from: 'M4A',
    to: 'WMA',
    fromExt: 'm4a',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → WMA Converter', tr: 'M4A → WMA Dönüştürücü' },
    aciklama: { en: 'Convert M4A files to WMA format.', tr: 'M4A dosyalarınızı WMA formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'm4a-to-opus',
    from: 'M4A',
    to: 'OPUS',
    fromExt: 'm4a',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'M4A → OPUS Converter', tr: 'M4A → OPUS Dönüştürücü' },
    aciklama: { en: 'Convert M4A files to OPUS format.', tr: 'M4A dosyalarınızı OPUS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wma-to-mp3',
    from: 'WMA',
    to: 'MP3',
    fromExt: 'wma',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → MP3 Converter', tr: 'WMA → MP3 Dönüştürücü' },
    aciklama: { en: 'Convert WMA files to MP3 format.', tr: 'WMA dosyalarınızı MP3 formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wma-to-wav',
    from: 'WMA',
    to: 'WAV',
    fromExt: 'wma',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → WAV Converter', tr: 'WMA → WAV Dönüştürücü' },
    aciklama: { en: 'Convert WMA files to WAV format.', tr: 'WMA dosyalarınızı WAV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wma-to-ogg',
    from: 'WMA',
    to: 'OGG',
    fromExt: 'wma',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → OGG Converter', tr: 'WMA → OGG Dönüştürücü' },
    aciklama: { en: 'Convert WMA files to OGG format.', tr: 'WMA dosyalarınızı OGG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wma-to-aac',
    from: 'WMA',
    to: 'AAC',
    fromExt: 'wma',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → AAC Converter', tr: 'WMA → AAC Dönüştürücü' },
    aciklama: { en: 'Convert WMA files to AAC format.', tr: 'WMA dosyalarınızı AAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wma-to-flac',
    from: 'WMA',
    to: 'FLAC',
    fromExt: 'wma',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → FLAC Converter', tr: 'WMA → FLAC Dönüştürücü' },
    aciklama: { en: 'Convert WMA files to lossless FLAC format.', tr: 'WMA dosyalarınızı kayıpsız FLAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wma-to-m4a',
    from: 'WMA',
    to: 'M4A',
    fromExt: 'wma',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → M4A Converter', tr: 'WMA → M4A Dönüştürücü' },
    aciklama: { en: 'Convert WMA files to M4A format.', tr: 'WMA dosyalarınızı M4A formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'wma-to-opus',
    from: 'WMA',
    to: 'OPUS',
    fromExt: 'wma',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMA → OPUS Converter', tr: 'WMA → OPUS Dönüştürücü' },
    aciklama: { en: 'Convert WMA files to OPUS format.', tr: 'WMA dosyalarınızı OPUS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'opus-to-mp3',
    from: 'OPUS',
    to: 'MP3',
    fromExt: 'opus',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → MP3 Converter', tr: 'OPUS → MP3 Dönüştürücü' },
    aciklama: { en: 'Convert OPUS files to MP3 format.', tr: 'OPUS dosyalarınızı MP3 formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'opus-to-wav',
    from: 'OPUS',
    to: 'WAV',
    fromExt: 'opus',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → WAV Converter', tr: 'OPUS → WAV Dönüştürücü' },
    aciklama: { en: 'Convert OPUS files to WAV format.', tr: 'OPUS dosyalarınızı WAV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'opus-to-ogg',
    from: 'OPUS',
    to: 'OGG',
    fromExt: 'opus',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → OGG Converter', tr: 'OPUS → OGG Dönüştürücü' },
    aciklama: { en: 'Convert OPUS files to OGG format.', tr: 'OPUS dosyalarınızı OGG formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'opus-to-aac',
    from: 'OPUS',
    to: 'AAC',
    fromExt: 'opus',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → AAC Converter', tr: 'OPUS → AAC Dönüştürücü' },
    aciklama: { en: 'Convert OPUS files to AAC format.', tr: 'OPUS dosyalarınızı AAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'opus-to-flac',
    from: 'OPUS',
    to: 'FLAC',
    fromExt: 'opus',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → FLAC Converter', tr: 'OPUS → FLAC Dönüştürücü' },
    aciklama: { en: 'Convert OPUS files to lossless FLAC format.', tr: 'OPUS dosyalarınızı kayıpsız FLAC formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'opus-to-m4a',
    from: 'OPUS',
    to: 'M4A',
    fromExt: 'opus',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → M4A Converter', tr: 'OPUS → M4A Dönüştürücü' },
    aciklama: { en: 'Convert OPUS files to M4A format.', tr: 'OPUS dosyalarınızı M4A formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'opus-to-wma',
    from: 'OPUS',
    to: 'WMA',
    fromExt: 'opus',
    toExt: 'wma',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'OPUS → WMA Converter', tr: 'OPUS → WMA Dönüştürücü' },
    aciklama: { en: 'Convert OPUS files to WMA format.', tr: 'OPUS dosyalarınızı WMA formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'mp4-to-wav',
    from: 'MP4',
    to: 'WAV',
    fromExt: 'mp4',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → WAV Converter', tr: 'MP4 → WAV Dönüştürücü' },
    aciklama: { en: 'Extract audio from MP4 video and save as WAV.', tr: 'MP4 videosundan ses çıkartın ve WAV olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mp4-to-ogg',
    from: 'MP4',
    to: 'OGG',
    fromExt: 'mp4',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → OGG Converter', tr: 'MP4 → OGG Dönüştürücü' },
    aciklama: { en: 'Extract audio from MP4 video and save as OGG.', tr: 'MP4 videosundan ses çıkartın ve OGG olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mp4-to-aac',
    from: 'MP4',
    to: 'AAC',
    fromExt: 'mp4',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → AAC Converter', tr: 'MP4 → AAC Dönüştürücü' },
    aciklama: { en: 'Extract audio from MP4 video and save as AAC.', tr: 'MP4 videosundan ses çıkartın ve AAC olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mp4-to-flac',
    from: 'MP4',
    to: 'FLAC',
    fromExt: 'mp4',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → FLAC Converter', tr: 'MP4 → FLAC Dönüştürücü' },
    aciklama: { en: 'Extract audio from MP4 video and save as FLAC.', tr: 'MP4 videosundan ses çıkartın ve FLAC olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mp4-to-m4a',
    from: 'MP4',
    to: 'M4A',
    fromExt: 'mp4',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → M4A Converter', tr: 'MP4 → M4A Dönüştürücü' },
    aciklama: { en: 'Extract audio from MP4 video and save as M4A.', tr: 'MP4 videosundan ses çıkartın ve M4A olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mp4-to-opus',
    from: 'MP4',
    to: 'OPUS',
    fromExt: 'mp4',
    toExt: 'opus',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MP4 → OPUS Converter', tr: 'MP4 → OPUS Dönüştürücü' },
    aciklama: { en: 'Extract audio from MP4 video and save as OPUS.', tr: 'MP4 videosundan ses çıkartın ve OPUS olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'webm-to-wav',
    from: 'WebM',
    to: 'WAV',
    fromExt: 'webm',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → WAV Converter', tr: 'WebM → WAV Dönüştürücü' },
    aciklama: { en: 'Extract audio from WebM video and save as WAV.', tr: 'WebM videosundan ses çıkartın ve WAV olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'webm-to-ogg',
    from: 'WebM',
    to: 'OGG',
    fromExt: 'webm',
    toExt: 'ogg',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → OGG Converter', tr: 'WebM → OGG Dönüştürücü' },
    aciklama: { en: 'Extract audio from WebM video and save as OGG.', tr: 'WebM videosundan ses çıkartın ve OGG olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'webm-to-aac',
    from: 'WebM',
    to: 'AAC',
    fromExt: 'webm',
    toExt: 'aac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WebM → AAC Converter', tr: 'WebM → AAC Dönüştürücü' },
    aciklama: { en: 'Extract audio from WebM video and save as AAC.', tr: 'WebM videosundan ses çıkartın ve AAC olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mov-to-mp3',
    from: 'MOV',
    to: 'MP3',
    fromExt: 'mov',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → MP3 Converter', tr: 'MOV → MP3 Dönüştürücü' },
    aciklama: { en: 'Extract audio from MOV video and save as MP3.', tr: 'MOV videosundan ses çıkartın ve MP3 olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mov-to-wav',
    from: 'MOV',
    to: 'WAV',
    fromExt: 'mov',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → WAV Converter', tr: 'MOV → WAV Dönüştürücü' },
    aciklama: { en: 'Extract audio from MOV video and save as WAV.', tr: 'MOV videosundan ses çıkartın ve WAV olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mov-to-m4a',
    from: 'MOV',
    to: 'M4A',
    fromExt: 'mov',
    toExt: 'm4a',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MOV → M4A Converter', tr: 'MOV → M4A Dönüştürücü' },
    aciklama: { en: 'Extract audio from MOV video and save as M4A.', tr: 'MOV videosundan ses çıkartın ve M4A olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'avi-to-mp3',
    from: 'AVI',
    to: 'MP3',
    fromExt: 'avi',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → MP3 Converter', tr: 'AVI → MP3 Dönüştürücü' },
    aciklama: { en: 'Extract audio from AVI video and save as MP3.', tr: 'AVI videosundan ses çıkartın ve MP3 olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'avi-to-wav',
    from: 'AVI',
    to: 'WAV',
    fromExt: 'avi',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'AVI → WAV Converter', tr: 'AVI → WAV Dönüştürücü' },
    aciklama: { en: 'Extract audio from AVI video and save as WAV.', tr: 'AVI videosundan ses çıkartın ve WAV olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mkv-to-mp3',
    from: 'MKV',
    to: 'MP3',
    fromExt: 'mkv',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → MP3 Converter', tr: 'MKV → MP3 Dönüştürücü' },
    aciklama: { en: 'Extract audio from MKV video and save as MP3.', tr: 'MKV videosundan ses çıkartın ve MP3 olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mkv-to-wav',
    from: 'MKV',
    to: 'WAV',
    fromExt: 'mkv',
    toExt: 'wav',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → WAV Converter', tr: 'MKV → WAV Dönüştürücü' },
    aciklama: { en: 'Extract audio from MKV video and save as WAV.', tr: 'MKV videosundan ses çıkartın ve WAV olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'mkv-to-flac',
    from: 'MKV',
    to: 'FLAC',
    fromExt: 'mkv',
    toExt: 'flac',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'MKV → FLAC Converter', tr: 'MKV → FLAC Dönüştürücü' },
    aciklama: { en: 'Extract audio from MKV video and save as FLAC.', tr: 'MKV videosundan ses çıkartın ve FLAC olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'flv-to-mp3',
    from: 'FLV',
    to: 'MP3',
    fromExt: 'flv',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'FLV → MP3 Converter', tr: 'FLV → MP3 Dönüştürücü' },
    aciklama: { en: 'Extract audio from FLV video and save as MP3.', tr: 'FLV videosundan ses çıkartın ve MP3 olarak kaydedin.' },
    populer: false,
  },
  {
    slug: 'wmv-to-mp3',
    from: 'WMV',
    to: 'MP3',
    fromExt: 'wmv',
    toExt: 'mp3',
    kategori: 'ses',
    converter: 'ffmpeg',
    baslik: { en: 'WMV → MP3 Converter', tr: 'WMV → MP3 Dönüştürücü' },
    aciklama: { en: 'Extract audio from WMV video and save as MP3.', tr: 'WMV videosundan ses çıkartın ve MP3 olarak kaydedin.' },
    populer: false,
  },


  {
    slug: 'mp3-to-txt',
    from: 'MP3',
    to: 'TXT',
    fromExt: 'mp3',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'MP3 → TXT (Speech to Text)', tr: 'MP3 → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your MP3 audio files to text using AI directly in your browser.', tr: 'MP3 ses dosyalarınızı tarayıcınızda yapay zeka ile yazıya dökün.' },
    populer: true,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },
  {
    slug: 'wav-to-txt',
    from: 'WAV',
    to: 'TXT',
    fromExt: 'wav',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'WAV → TXT (Speech to Text)', tr: 'WAV → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your WAV audio files to text using AI directly in your browser.', tr: 'WAV ses dosyalarınızı tarayıcınızda yapay zeka ile yazıya dökün.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },
  {
    slug: 'ogg-to-txt',
    from: 'OGG',
    to: 'TXT',
    fromExt: 'ogg',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'OGG → TXT (Speech to Text)', tr: 'OGG → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your OGG audio files to text using AI.', tr: 'OGG ses dosyalarınızı yapay zeka ile yazıya dökün.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },
  {
    slug: 'm4a-to-txt',
    from: 'M4A',
    to: 'TXT',
    fromExt: 'm4a',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'M4A → TXT (Speech to Text)', tr: 'M4A → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your M4A audio files to text using AI.', tr: 'M4A ses dosyalarınızı yapay zeka ile yazıya dökün.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },
  {
    slug: 'aac-to-txt',
    from: 'AAC',
    to: 'TXT',
    fromExt: 'aac',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'AAC → TXT (Speech to Text)', tr: 'AAC → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your AAC audio files to text using AI.', tr: 'AAC ses dosyalarınızı yapay zeka ile yazıya dökün.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },
  {
    slug: 'flac-to-txt',
    from: 'FLAC',
    to: 'TXT',
    fromExt: 'flac',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'FLAC → TXT (Speech to Text)', tr: 'FLAC → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your FLAC audio files to text using AI.', tr: 'FLAC ses dosyalarınızı yapay zeka ile yazıya dökün.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },
  {
    slug: 'opus-to-txt',
    from: 'OPUS',
    to: 'TXT',
    fromExt: 'opus',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'OPUS → TXT (Speech to Text)', tr: 'OPUS → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your OPUS audio files to text using AI.', tr: 'OPUS ses dosyalarınızı yapay zeka ile yazıya dökün.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },
  {
    slug: 'wma-to-txt',
    from: 'WMA',
    to: 'TXT',
    fromExt: 'wma',
    toExt: 'txt',
    kategori: 'ses',
    converter: 'whisper',
    baslik: { en: 'WMA → TXT (Speech to Text)', tr: 'WMA → TXT (Sesi Yazıya Dök)' },
    aciklama: { en: 'Transcribe your WMA audio files to text using AI.', tr: 'WMA ses dosyalarınızı yapay zeka ile yazıya dökün.' },
    populer: false,
    secenekler: [
      {
        id: 'language',
        label: { en: 'Audio Language', tr: 'Ses Dili' },
        type: 'select',
        default: 'turkish',
        options: [
          { value: 'turkish', label: 'Türkçe' },
          { value: 'english', label: 'English' },
          { value: 'auto', label: 'Auto Detect' }
        ]
      }
    ]
  },


  // ===== BELGE =====
  {
    slug: 'images-to-pdf',
    from: 'Görseller',
    to: 'PDF',
    fromExt: 'jpg',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'Convert Images to PDF', tr: 'Görselleri PDF\'ye Dönüştür' },
    aciklama: { en: 'Combine your JPG or PNG images into a single PDF file.', tr: 'JPG veya PNG görsellerinizi tek bir PDF dosyasında birleştirin.' },
    populer: true,
    cokluDosya: true,
  },
  {
    slug: 'pdf-to-images',
    from: 'PDF',
    to: 'Görseller',
    fromExt: 'pdf',
    toExt: 'png',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'PDF → Image Converter', tr: 'PDF → Görsel Dönüştürücü' },
    aciklama: { en: 'Convert your PDF pages to separate PNG images.', tr: 'PDF sayfalarınızı ayrı PNG görsellerine dönüştürün.' },
    populer: false,
  },
  {
    slug: 'merge-pdf',
    from: 'PDF',
    to: 'PDF',
    fromExt: 'pdf',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'PDF Merger', tr: 'PDF Birleştirici' },
    aciklama: { en: 'Merge multiple PDF files into a single PDF.', tr: 'Birden fazla PDF dosyasını tek bir PDF\'de birleştirin.' },
    populer: true,
    cokluDosya: true,
  },
  {
    slug: 'split-pdf',
    from: 'PDF',
    to: 'PDF',
    fromExt: 'pdf',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'PDF Splitter', tr: 'PDF Bölücü' },
    aciklama: { en: 'Split your PDF file into separate pages.', tr: 'PDF dosyanızı sayfa sayfa ayrı dosyalara bölün.' },
    populer: false,
  },
  {
    slug: 'text-to-pdf',
    from: 'TXT',
    to: 'PDF',
    fromExt: 'txt',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'Text → PDF Converter', tr: 'Metin → PDF Dönüştürücü' },
    aciklama: { en: 'Convert your text files to professional PDF documents.', tr: 'Metin dosyalarınızı profesyonel PDF belgelerine dönüştürün.' },
    populer: false,
  },
  {
    slug: 'docx-to-html',
    from: 'DOCX',
    to: 'HTML',
    fromExt: 'docx',
    toExt: 'html',
    kategori: 'belge',
    converter: 'mammoth',
    baslik: { en: 'DOCX → HTML Converter', tr: 'DOCX → HTML Dönüştürücü' },
    aciklama: { en: 'Convert your Word documents to clean HTML code.', tr: 'Word belgelerinizi temiz HTML koduna dönüştürün.' },
    populer: false,
  },
  {
    slug: 'excel-to-csv',
    from: 'Excel',
    to: 'CSV',
    fromExt: 'xlsx',
    toExt: 'csv',
    kategori: 'belge',
    converter: 'sheetjs',
    baslik: { en: 'Excel → CSV Converter', tr: 'Excel → CSV Dönüştürücü' },
    aciklama: { en: 'Convert your Excel spreadsheets to CSV format.', tr: 'Excel tablolarınızı CSV formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'csv-to-excel',
    from: 'CSV',
    to: 'Excel',
    fromExt: 'csv',
    toExt: 'xlsx',
    kategori: 'belge',
    converter: 'sheetjs',
    baslik: { en: 'CSV → Excel Converter', tr: 'CSV → Excel Dönüştürücü' },
    aciklama: { en: 'Convert your CSV files to Excel format.', tr: 'CSV dosyalarınızı Excel formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'docx-to-pdf',
    from: 'DOCX',
    to: 'PDF',
    fromExt: 'docx',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'DOCX → PDF Converter', tr: 'DOCX → PDF Dönüştürücü' },
    aciklama: { en: 'Convert Word document (.docx) to PDF format.', tr: 'Word belgesini (.docx) PDF formatına dönüştürün.' },
    populer: true,
  },
  {
    slug: 'html-to-pdf',
    from: 'HTML',
    to: 'PDF',
    fromExt: 'html',
    toExt: 'pdf',
    kategori: 'belge',
    converter: 'pdf-lib',
    baslik: { en: 'HTML → PDF Converter', tr: 'HTML → PDF Dönüştürücü' },
    aciklama: { en: 'Convert HTML files to PDF format.', tr: 'HTML dosyalarınızı PDF formatına dönüştürün.' },
    populer: false,
  },


  // ===== ARŞİV =====
  {
    slug: 'files-to-zip',
    from: 'Dosyalar',
    to: 'ZIP',
    fromExt: '*',
    toExt: 'zip',
    kategori: 'arsiv',
    converter: 'jszip',
    baslik: { en: 'Zip Files', tr: 'Dosyaları ZIP\'le' },
    aciklama: { en: 'Compress multiple files into a single ZIP archive.', tr: 'Birden fazla dosyayı tek bir ZIP arşivinde sıkıştırın.' },
    populer: false,
    cokluDosya: true,
  },
  {
    slug: 'extract-zip',
    from: 'ZIP',
    to: 'Dosyalar',
    fromExt: 'zip',
    toExt: '*',
    kategori: 'arsiv',
    converter: 'jszip',
    baslik: { en: 'Extract ZIP', tr: 'ZIP Çıkart' },
    aciklama: { en: 'Extract ZIP archives and access your files.', tr: 'ZIP arşivlerini çıkartın ve dosyalarınıza erişin.' },
    populer: false,
  },

  // ===== ALTYAZI =====
  {
    slug: 'srt-to-vtt',
    from: 'SRT',
    to: 'VTT',
    fromExt: 'srt',
    toExt: 'vtt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SRT → VTT Converter', tr: 'SRT → VTT Dönüştürücü' },
    aciklama: { en: 'Convert your SRT subtitle files to HTML5-compatible WebVTT (VTT) format.', tr: 'SRT altyazı dosyalarınızı HTML5 uyumlu WebVTT (VTT) formatına dönüştürün.' },
    populer: true,
  },
  {
    slug: 'vtt-to-srt',
    from: 'VTT',
    to: 'SRT',
    fromExt: 'vtt',
    toExt: 'srt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'VTT → SRT Converter', tr: 'VTT → SRT Dönüştürücü' },
    aciklama: { en: 'Convert your VTT subtitles to the most common format, SRT.', tr: 'VTT altyazılarınızı en yaygın format olan SRT\'ye dönüştürün.' },
    populer: true,
  },
  {
    slug: 'srt-to-ass',
    from: 'SRT',
    to: 'ASS',
    fromExt: 'srt',
    toExt: 'ass',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SRT → ASS Converter', tr: 'SRT → ASS Dönüştürücü' },
    aciklama: { en: 'Convert your SRT files to ASS format with advanced styling support.', tr: 'SRT dosyalarınızı gelişmiş stil desteği olan ASS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ass-to-srt',
    from: 'ASS',
    to: 'SRT',
    fromExt: 'ass',
    toExt: 'srt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'ASS → SRT Converter', tr: 'ASS → SRT Dönüştürücü' },
    aciklama: { en: 'Convert your ASS files to standard SRT format.', tr: 'ASS dosyalarınızı standart SRT formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'sub-to-srt',
    from: 'SUB',
    to: 'SRT',
    fromExt: 'sub',
    toExt: 'srt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SUB → SRT Converter', tr: 'SUB → SRT Dönüştürücü' },
    aciklama: { en: 'Convert your old SUB subtitles to the common SRT format.', tr: 'Eski SUB altyazılarınızı yaygın SRT formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'srt-to-sub',
    from: 'SRT',
    to: 'SUB',
    fromExt: 'srt',
    toExt: 'sub',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SRT → SUB Converter', tr: 'SRT → SUB Dönüştürücü' },
    aciklama: { en: 'Convert your SRT subtitles to SUB format.', tr: 'SRT altyazılarınızı SUB formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'vtt-to-ass',
    from: 'VTT',
    to: 'ASS',
    fromExt: 'vtt',
    toExt: 'ass',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'VTT → ASS Converter', tr: 'VTT → ASS Dönüştürücü' },
    aciklama: { en: 'Convert your VTT subtitles to ASS format.', tr: 'VTT altyazılarınızı ASS formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'vtt-to-sub',
    from: 'VTT',
    to: 'SUB',
    fromExt: 'vtt',
    toExt: 'sub',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'VTT → SUB Converter', tr: 'VTT → SUB Dönüştürücü' },
    aciklama: { en: 'Convert your VTT subtitles to SUB format.', tr: 'VTT altyazılarınızı SUB formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ass-to-vtt',
    from: 'ASS',
    to: 'VTT',
    fromExt: 'ass',
    toExt: 'vtt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'ASS → VTT Converter', tr: 'ASS → VTT Dönüştürücü' },
    aciklama: { en: 'Convert your ASS subtitles to WebVTT (VTT) format.', tr: 'ASS altyazılarınızı WebVTT (VTT) formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'ass-to-sub',
    from: 'ASS',
    to: 'SUB',
    fromExt: 'ass',
    toExt: 'sub',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'ASS → SUB Converter', tr: 'ASS → SUB Dönüştürücü' },
    aciklama: { en: 'Convert your ASS subtitles to SUB format.', tr: 'ASS altyazılarınızı SUB formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'sub-to-vtt',
    from: 'SUB',
    to: 'VTT',
    fromExt: 'sub',
    toExt: 'vtt',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SUB → VTT Converter', tr: 'SUB → VTT Dönüştürücü' },
    aciklama: { en: 'Convert your SUB subtitles to WebVTT (VTT) format.', tr: 'SUB altyazılarınızı WebVTT (VTT) formatına dönüştürün.' },
    populer: false,
  },
  {
    slug: 'sub-to-ass',
    from: 'SUB',
    to: 'ASS',
    fromExt: 'sub',
    toExt: 'ass',
    kategori: 'altyazi',
    converter: 'subsrt',
    baslik: { en: 'SUB → ASS Converter', tr: 'SUB → ASS Dönüştürücü' },
    aciklama: { en: 'Convert your SUB subtitles to ASS format.', tr: 'SUB altyazılarınızı ASS formatına dönüştürün.' },
    populer: false,
  },

];

// Yardımcı fonksiyonlar
export function getDonusumBySlug(slug: string): DonusumCift | undefined {
  return DONUSUM_DATA.find((d) => d.slug === slug);
}

export function getDonusumlerByKategori(kategori: KategoriSlug): DonusumCift[] {
  return DONUSUM_DATA.filter((d) => d.kategori === kategori);
}

export function getKategoriBySlug(slug: string): Kategori | undefined {
  return KATEGORILER.find((k) => k.slug === slug);
}

export function getPopulerDonusumler(): DonusumCift[] {
  return DONUSUM_DATA.filter((d) => d.populer);
}

export function getIlgiliDonusumler(current: DonusumCift, limit = 6): DonusumCift[] {
  return DONUSUM_DATA.filter(
    (d) =>
      d.slug !== current.slug &&
      (d.kategori === current.kategori ||
        d.fromExt === current.fromExt ||
        d.toExt === current.toExt)
  ).slice(0, limit);
}

// Format renkleri
export function getFormatRenk(format: string): string {
  const map: Record<string, string> = {
    JPG: 'var(--r)',
    JPEG: 'var(--r)',
    PNG: 'var(--b)',
    WebP: 'var(--g)',
    HEIC: 'var(--p)',
    SVG: 'var(--o)',
    BMP: 'var(--y)',
    GIF: 'var(--o)',
    MP4: 'var(--r)',
    WebM: 'var(--g)',
    AVI: 'var(--y)',
    MOV: 'var(--p)',
    MKV: 'var(--b)',
    FLV: 'var(--y)',
    WMV: 'var(--p)',
    MP3: 'var(--o)',
    WAV: 'var(--b)',
    OGG: 'var(--g)',
    FLAC: 'var(--p)',
    AAC: 'var(--y)',
    WMA: 'var(--muted)',
    OPUS: 'var(--g)',
    PDF: 'var(--r)',
    DOCX: 'var(--b)',
    HTML: 'var(--o)',
    TXT: 'var(--muted)',
    M4A: 'var(--b)',

    CSV: 'var(--g)',
    Excel: 'var(--g)',
    XLSX: 'var(--g)',
    ZIP: 'var(--y)',
    Görseller: 'var(--p)',
    Dosyalar: 'var(--b)',
    SRT: 'var(--r)',
    VTT: 'var(--g)',
    ASS: 'var(--p)',
    SUB: 'var(--y)',
  };
  return map[format] || 'var(--muted)';
}
